
require File.dirname(__FILE__) + "/_buildassist"

deferred, prefetched, inlined = detect_modules

config :all, 
	:required => :foundation,
	:target_types => {
		:frameworks => :framework,
		:modules => :module,
		:plugins => :module,
		:xbos => :module
	}
	
config :xt,
	:required => [ :plugin, :xbo, :table ],
	:deferred_modules => deferred,
	:inlined_modules => inlined,
    :prefetched_modules => prefetched
