enyo.depends(
  "document.js",
  "account.js",
  "address.js",
  "contact.js",
  "currency.js",
  "file.js",
  "image.js",
  "incident.js",
  "item.js",
  "opportunity.js",
  "priority.js",
  "project.js",
  "sales_rep.js",
  "tax_authority.js",
  "to_do.js",
  "url.js",
  "user_account.js"
);