enyo.depends(
  "Document.js",
  "Account.js",
  "Address.js",
  "Contact.js",
  "File.js",
  "Image.js",
  "Incident.js",
  "Item.js",
  "Opportunity.js",
  "Priority.js",
  "Project.js",
  "ToDo.js",
  "Url.js",
  "UserAccount.js"
);