enyo.depends(
  "account.js",
  "characteristic.js",
  "contact.js",
  "customer.js",
  "incident.js",
  "opportunity.js",
  "project.js",
  "quote.js",
  "sales_order.js",
  "to_do.js",
  "startup.js"
);
