enyo.depends(
  "$lib/underscore",
  "$lib/backbone",
  "$lib/backbone_relational",
  "$lib/layout",
  "$lib/onyx",
  "$lib/globalize",
  "$lib/gts-plugins/DatePicker",
  "$lib/date_format",
  "$lib/socket.io",
  "xt",
  "xm",
  "xv",
  "app.js",
  "$lib/onyx/source/wip-package.js"
);