enyo.depends(
  "$lib/underscore",
  "$lib/backbone",
  "$lib/backbone_relational",
  "$lib/layout",
  "$lib/onyx",
  "$lib/onyx/source/wip-package.js",
  "$lib/globalize",
  "$lib/enyo_2_components",
  "$lib/socket.io",
  "xt",
  "xm",
  "xv",
  "app.js"
);
