enyo.depends(
  "$lib/underscore",
  "$lib/backbone",
  "$lib/backbone_relational",
  "$lib/layout",
  "$lib/onyx",
  "$lib/socket.io",
  "$lib/Enyo-2-Components/addons/DatePicker/package.js",
  "$lib/Enyo-2-Components/addons/calendarSelector/package.js",
  "xt",
  "xm",
  "app.js"
);
