// ==========================================================================
// Project:   XT` Strings
// Copyright: ©2011 OpenMFG LLC, d/b/a xTuple
// ==========================================================================
/*globals XT */

// Place strings you want to localize here.  In your app, use the key and
// localize it using "key string".loc().  HINT: For your key names, use the
// english string with an underscore in front.  This way you can still see
// how your UI will look and you'll notice right away when something needs a
// localized string added to this file!
//

var lang = XT.stringsFor("en_US", {

  // ********
  // Labels
  // ********

  "_above": "Above",
  "_abbreviation": "Abbreviation",
  "_abbreviationLong": "Abbreviation Long",
  "_abbreviationShort": "Abbreviation Short",
  "_account": "Account",
  "_accountNumber": "Account Number",
  "_accountNumberGeneration": "Account Number Generation",
  "_accountType": "Account Type",
  "_accounts": "Accounts",
  "_active": "Active",
  "_actual": "Actual",
  "_actualClose": "Actual Close",
  "_actualExpenses": "Actual Expenses",
  "_actualExpensesTotal": "Total Expenses Actual",
  "_actualHours": "Actual Hours",
  "_actualHoursTotal": "Total Hours Actual",
  "_additional": "Additional",
  "_address": "Address",
  "_address1": "Address1",
  "_address2": "Address2",
  "_addressCharacteristic": "Address Characteristic",
  "_addressComment": "Address Comment",
  "_addresses": "Addresses",
  "_alarms": "Alarms",
  "_altEmphasisColor": "Alt Emphasis Color",
  "_alternate": "Alternate",
  "_alternateAddresses": "Alternate Addresses",
  "_amount": "Amount",
  "_array": "Array",
  "_assignDate": "Assign Date",
  "_assigned": "Assigned",
  "_assignedTo": "Assigned To",
  "_attach": "Attach",
  "_automatic": "Automatic",
  "_automaticAllowOverride": "Automatic Allow Override",
  "_balance": "Balance",
  "_balanceExpensesTotal": "Balance Expenses Total",
  "_balanceHoursTotal": "Balance Hours Total",
  "_boolean": "Boolean",
  "_budgeted": "Budgeted",
  "_budgetedExpenses": "Budgeted Expenses",
  "_budgetedExpensesTotal": "Total Expenses Budgeted",
  "_budgetedHours": "Budgeted Hours",
  "_budgetedHoursTotal": "Total Hours Budgeted",
  "_canCreateUsers": "Can Create Users",
  "_category": "Category",
  "_characteristic": "Characteristic",
  "_characteristicType": "Characteristic Type",
  "_characteristicOption": "Characteristic Option",
  "_classCode": "Class Code",
  "_classCodes": "Class Codes",
  "_closeDate": "Close Date",
  "_closed": "Closed",
  "_code": "Code",
  "_configure": "Configure",
  "_commentType": "Comment Type",
  "_commentsEditable": "Comments Editable",
  "_company": "Company",
  "_completeDate": "Complete Date",
  "_contact": "Contact",
  "_contactRelations": "Contacts",
  "_contacts": "Contacts",
  "_countries": "Countries",
  "_created": "Created",
  "_createdBy": "Created By",
  "_currencies": "Currencies",
  "_currency": "Currency",
  "_currencyAbbreviation": "Currency Abbreviation",
  "_currencyName": "Currency Name",
  "_currencyNumber": "Currency Number",
  "_currencySymbol": "Currency Symbol",
  "_customer": "Customer",
  "_customers": "Customers",
  "_dashboard": "Dashboard",
  "_data": "Data",
  "_dataState": "Data State",
  "_date": "Date",
  "_deactivate": "Deactivate",
  "_deferred": "Deferred",
  "_detach": "Detach",
  "_description": "Description",
  "_description1": "Description1",
  "_description2": "Description2",
  "_disableExport": "Disable Export",
  "_document": "Document",
  "_documentDate": "Document Date",
  "_documentNumber": "Document #",
  "_documentType": "Document Type",
  "_dueDate": "Due Date",
  "_dueDays": "Due Days",
  "_effective": "Effective",
  "_email": "Email",
  "_emphasisColor": "Emphasis Color",
  "_employee": "Employee",
  "_employees": "Employees",
  "_enabled": "Enabled?",
  "_end": "End",
  "_endBalance": "End Balance",
  "_ending": "Ending",
  "_endingLabel": "Ending Label",
  "_equals": "Equals",
  "_error": "Error",
  "_errorColor": "Error Color",
  "_eventRecipient": "Event Recipient",
  "_expenses": "Expenses",
  "_expiredColor": "Expired Color",
  "_expires": "Expires",
  "_extended": "Extended",
  "_extendedDescription": "Extended Description",
  "_extendedPriceScale": "Extended Price Scale",
  "_externalReference": "External Reference",
  "_fax": "Fax",
  "_file": "File",
  "_files": "Files",
  "_filter": "Filter",
  "_filterBy": "Filter By",
  "_firstName": "First Name",
  "_for": "For",
  "_fractional": "Fractional",
  "_frequency": "Frequency",
  "_from": "From",
  "_fromDate": "From Date",
  "_futureColor": "Future Color",
  "_grantedPrivileges": "Granted Privileges",
  "_grantedUserAccountRoles": "Granted User Account Roles",
  "_groupSequence": "Group Sequence",
  "_groups": "Groups",
  "_history": "History",
  "_home": "Home",
  "_honorific": "Honorific",
  "_honorifics": "Honorifics",
  "_hours": "Hours",
  "_hrs": "hrs.",
  "_image": "Image",
  "_images": "Images",
  "_incident": "Incident",
  "_incidentRelations": "Incidents",
  "_incidents": "Incidents",
  "_incidentCategories": "Incident Categories",
  "_incidentCategory": "Incident Category",
  "_incidentHistory": "Incident History",
  "_incidentResolution": "Incident Resolution",
  "_incidentResolutions": "Incident Resolutions",
  "_incidentSeverities": "Incident Severities",
  "_incidentSeverity": "Incident Severity",
  "_incidentStatus": "Status",
  "_incidentNumberGeneration": "Incident Number Generation",
  "_incidentsPublicByDefault": "Incidents public by default",
  "_incidentsShowPublicCheckbox": "Incidents show public checkbox",
  "_information": "Information",
  "_initials": "Initials",
  "_inventoryUnit": "Inventory Unit",
  "_isActive": "Active",
  "_isAddresses": "Addresses",
  "_isBase": "Base",
  "_isContacts": "Contacts",
  "_isDefault": "Default",
  "_isDeleted": "Deleted",
  "_isEvent": "Event",
  "_isFractional": "Fractional",
  "_isIncidents": "Incidents",
  "_isItemWeight": "Item Weight",
  "_isItems": "Items",
  "_isMessage": "Message",
  "_isOpportunities": "Opportunities",
  "_isPosted": "Posted",
  "_isPrinted": "Printed",
  "_isPublic": "Public",
  "_isSold": "Sold",
  "_item": "Item",
  "_itemConversion": "Item Conversion",
  "_itemNumber": "Item Number",
  "_itemUnitConversion": "Item Unit Conversion",
  "_itemUnitType": "Item Unit Type",
  "_items": "Items",
  "_jobTitle": "Job Title",
  "_language": "Language",
  "_lastName": "Last Name",
  "_line1": "Line1",
  "_line2": "Line2",
  "_line3": "Line3",
  "_lineNumber": "Line Number",
  "_lines": "Lines",
  "_listPrice": "List Price",
  "_locale": "Locale",
  "_login": "Login",
  "_logout": "Logout",
  "_mainAddress": "Main Address",
  "_manual": "Manual",
  "_mask": "Mask",
  "_match": "Match",
  "_maximum": "Maximum",
  "_menu": "Menu",
  "_messageRecipient": "Message Recipient",
  "_middleName": "Middle Name",
  "_module": "Module",
  "_monthExpire": "Month Expire",
  "_multiple": "Multiple",
  "_name": "Name",
  "_neither": "Neither",
  "_nextNumber": "Next #",
  "_nextCheckNumber": "Next Check Number",
  "_notes": "Notes",
  "_number": "Number",
  "_object": "Object",
  "_offset": "Offset",
  "_other": "Other",
  "_openBalance": "Open Balance",
  "_openDate": "Open Date",
  "_opportunities": "Opportunities",
  "_opportunity": "Opportunity",
  "_opportunityChangeLog": "Post Opportunity changes to Change Log",
  "_opportunityRelations": "Opportunities",
  "_opportunitySource": "Opportunity Source",
  "_opportunitySources": "Opportunity Sources",
  "_opportunityStage": "Opportunity Stage",
  "_opportunityStages": "Opportunity Stages",
  "_opportunityType": "Opportunity Type",
  "_opportunityTypes": "Opportunity Types",
  "_open": "Open",
  "_options": "Options",
  "_order": "Order",
  "_orderDate": "Order Date",
  "_orderNumber": "Order Number",
  "_ordered": "Ordered",
  "_owner": "Owner",
  "_paid": "Paid",
  "_password": "Password",
  "_path": "Path",
  "_pending": "Pending",
  "_percent": "Percent",
  "_period": "Period",
  "_phone": "Phone",
  "_pleaseLogin": "Please Login",
  "_postbooks": "PostBooks",
  "_price": "Price",
  "_priceUnit": "Price Unit",
  "_priceUnitRatio": "Price Unit Ratio",
  "_primaryContact": "Primary Contact",
  "_primaryEmail": "Primary Email",
  "_printed": "Printed",
  "_priority": "Priority",
  "_priorities": "Priorities",
  "_privilege": "Privilege",
  "_privileges": "Privileges",
  "_probability": "Probability",
  "_productCategories": "Product Categories",
  "_productCategory": "Product Category",
  "_profitCenter": "Profit Center",
  "_project": "Project",
  "_projectAssignedTo": "Project Assigned To",
  "_projectOwner": "Project Owner",
  "_projectRelations": "Projects",
  "_projectStatus": "Project Status",
  "_projectTask": "Project Task",
  "_projectTasks": "Project Tasks",
  "_projectTaskStatus": "Project Task Status",
  "_projects": "Projects",
  "_properName": "Proper Name",
  "_propername": "Propername",
  "_purchaseOrderNumber": "Purchase Order",
  "_required": "Required",
  "_qualifier": "Qualifier",
  "_quantity": "Quantity",
  "_recurrences": "Recurrences",
  "_recurring": "Recurring",
  "_reference": "Reference",
  "_relationships": "Relationships",
  "_replyTo": "Reply To",
  "_resolution": "Resolution",
  "_roles": "Roles",
  "_schedule": "Schedule",
  "_secondaryContact": "Secondary Contact",
  "_selectOrganization": "Select Organization",
  "_sense": "Sense",
  "_series": "Series",
  "_sessionTimedOut": "Your session has timed out",
  "_setup": "Setup",
  "_severity": "Severity",
  "_showCompleted": "Show Complete",
  "_showCompletedOnly": "Show Complete Only",
  "_showInactive": "Show Inactive",
  "_sold": "Sold",
  "_source": "Source",
  "_sourceType": "Source Type",
  "_stage": "Stage",
  "_start": "Start",
  "_startDate": "Start Date",
  "_states": "States",
  "_status": "Status",
  "_string": "String",
  "_suffix": "Suffix",
  "_summary": "Summary",
  "_symbol": "Symbol",
  "_system": "System",
  "_target": "Target",
  "_targetClose": "Target Close",
  "_targetType": "Target Type",
  "_tasks": "Tasks",
  "_taxAuthority": "Tax Authority",
  "_text": "Text",
  "_time": "Time",
  "_to": "To",
  "_toDate": "To Date",
  "_toDo": "To Do",
  "_toDoRelations": "To Dos",
  "_toDoStatus": "To Do Status",
  "_toDos": "To Dos",
  "_total": "Total",
  "_totals": "Totals",
  "_toUnit": "To Unit",
  "_trigger": "Trigger",
  "_type": "Type",
  "_unit": "Unit",
  "_units": "Units",
  "_unitType": "Unit Type",
  "_unknown": "(unknown)",
  "_updated": "Updated",
  "_updatedBy": "Updated By",
  "_url": "Link",
  "_urls": "Links",
  "_useDescription": "Use Description",
  "_userAccount": "User Account",
  "_userAccounts": "User Accounts",
  "_userAccountRole": "User Account Role",
  "_userAccountRoles": "User Account Roles",
  "_username": "Username",
  "_validator": "Validator",
  "_value": "Value",
  "_warningColor": "Warning Color",
  "_web": "Web",
  "_webAddress": "Web Address",
  "_welcome": "Welcome",
  "_xtuplePostbooks": "PostBooks",

  // ********
  // Messages
  // ********

  "_exitPageWarning": "You are about to leave the xTuple application.",
  "_loadingApplicationData": "Loading Application Data",
  "_loadingExtensions": "Loading Extensions",
  "_loadingSchema": "Loading Schema",
  "_loadingSessionData": "Loading Session Data",
  "_noAccountName": "No Account Name",
  "_noAddress": "No Address",
  "_noCategory": "No Category",
  "_noCloseTarget": "No Close Target",
  "_noContact": "No Contact",
  "_noEmail": "No Email",
  "_noJobTitle": "No Job Title",
  "_noName": "No Name",
  "_noNumber": "No Number",
  "_noPhone": "No Phone",
  "_noPriority": "No Priority",
  "_noSalesRep": "No Sales Rep",
  "_noSeverity": "No Severity",
  "_noStage": "No Stage",
  "_noTerms": "No Terms",
  "_noType": "No Type",

  // ********
  // Permissions
  // ********
  "_configureCRM": "Configure CRM",
  "_configureImportExport": "Configure Import Export",
  "_configurePM": "Configure Project",
  "_createNewCurrency": "Create New Currency",
  "_deleteItemMasters": "Delete Item Masters",
  "_editOthersComments": "Edit Others Comments",
  "_editOwnComments": "Edit Own Comments",
  "_editOwner": "Edit Owner",
  "_maintainAddresses": "Maintain Addresses",
  "_maintainAllCRMAccounts": "Maintain All Accounts",
  "_maintainAllContacts": "Maintain All Contacts",
  "_maintainAllIncidents": "Maintain All Incidents",
  "_maintainAllOpportunities": "Maintain All Opportunities",
  "_maintainAllProjects": "Maintain All Projects",
  "_maintainAllToDoItems": "Maintain All To-Do Items",
  "_maintainClassCodes": "Maintain Class Codes",
  "_maintainCommentTypes": "Maintain Comment Types",
  "_maintainCountries": "Maintain Countries",
  "_maintainCurrencies": "Maintain Currencies",
  "_maintainCurrencyRates": "Maintain Currency Rates",
  "_maintainImages": "Maintain Images",
  "_maintainItemMasters": "Maintain Item Masters",
  "_maintainProductCategories": "Maintain Product Categories",
  "_maintainStates": "Maintain States",
  "_maintainUOMs": "Maintain Units of Measure",
  "_maintainUsers": "Maintain Users",
  "_maintainIncidentCategories": "Maintain Incident Categories",
  "_maintainIncidentPriorities": "Maintain Incident Priorities",
  "_maintainIncidentResolutions": "Maintain Incident Resolutions",
  "_maintainIncidentSeverities": "Maintain Incident Severities",
  "_maintainOpportunitySources": "Maintain Opportunity Sources",
  "_maintainOpportunityStages": "Maintain Opportunity Stages",
  "_maintainOpportunityTypes": "Maintain Opportunity Types",
  "_maintainPartners": "Maintain Partners",
  "_maintainPersonalCRMAccounts": "Maintain Personal Accounts",
  "_maintainPersonalContacts": "Maintain Personal Contacts",
  "_maintainPersonalIncidents": "Maintain Personal Incidents",
  "_maintainPersonalOpportunities": "Maintain Personal Opportunities",
  "_maintainPersonalProjects": "Maintain Personal Projects",
  "_maintainPersonalToDoItems": "Maintain Personal To-Do Items",
  "_maintainTitles": "Maintain Titles",
  "_reassignToDoItems": "Reassign To-Do Items",
  "_viewAddresses": "View Addresses",
  "_viewAllCRMAccounts": "View All Accounts",
  "_viewAllContacts": "View All Contacts",
  "_viewAllIncidents": "View All Incidents",
  "_viewAllOpportunities": "View All Opportunities",
  "_viewAllProjects": "View All Projects",
  "_viewAllToDoItems": "View All To-Do Items",
  "_viewClassCodes": "View Class Codes",
  "_viewCurrencyRates": "View Currency Rates",
  "_viewDepartments": "View Departments",
  "_viewItemMasters": "View Item Masters",
  "_viewPersonalCRMAccounts": "View Personal Accounts",
  "_viewPersonalContacts": "View Personal Contacts",
  "_viewPersonalIncidents": "View Personal Incidents",
  "_viewPersonalOpportunities": "View Personal Opportunities",
  "_viewPersonalProjects": "View Personal Projects",
  "_viewPersonalToDoItems": "View Personal To-Do Items",
  "_viewProductCategories": "View Product Categories",
  "_viewUOMs": "View Units of Measure",
  "_viewTitles": "View Honorifics"
});
