// ==========================================================================
// Project:   XT` Strings
// Copyright: ©2011 OpenMFG LLC, d/b/a xTuple
// ==========================================================================
/*globals XT */

// Place strings you want to localize here.  In your app, use the key and
// localize it using "key string".loc().  HINT: For your key names, use the
// english string with an underscore in front.  This way you can still see
// how your UI will look and you'll notice right away when something needs a
// localized string added to this file!
//

var lang = XT.stringsFor("en_US", {
  "_allowAvgCostMethod": "Average",
  "_allowDups": "Allow Dups.",
  "_allowJobCostMethod": "Job",
  "_allowReceiptCostOverride": "Allow Inventory Receipt Cost Override (Avg. costing method only)",
  "_allowStdCostMethod": "Standard",
  "_backlog": "Backlog",
  "_costing": "Costing",
  "_countAvgCostMethod": "Cost to Use When Posting Count Tag for Avg. Cost Items",
  "_countSlipAuditing": "Count Slip # Auditing",
  "_defaultEventFence": "Default Event Fence (Days)",
  "_disableReceiptExcessQty": "Disallow PO Receipt of Qty greater than ordered",
  "_dontPost": "Do Not Post",
  "_enableAsOfQOH": "Enable As-Of QOH Reporting",
  "_enterReceipt": "Enter Receipt",
  "_inventory": "Inventory",
	"_inventoryDescription": "Shipping and Receiving, Inventory and Cost Management",
  "_isLocationControl": "Location Control",
  "_isReceiveLocationAuto": "Auto",
  "_isStockLocationAuto": "Auto",
  "_isIssueLocationAuto": "Auto",
  "_issue": "Issue",
  "_issueLocation": "Issue Location",
  "_issueLine": "Issue Line",
  "_issueStock": "Issue Stock",
  "_issueToShipping": "Issue to Shipping",
  "_kitComponentInheritCOS": "Kit Components Inherit COS from Kit Parent",
  "_leadTime": "Lead Time",
  "_location": "Location",
  "_locationComment": "Location Comment",
  "_maximumOrderQuantity": "Maximum Order Quantity",
  "_minimumOrderQuantity": "Minimum Order Quantity",
  "_noUnpostedSlipDupsSite": "No Unposted Dups. in a Site",
  "_noUnpostedSlipDups": "No Unposted Dups.",
  "_noSlipDupsSite": "No Dups. in a Site",
  "_nextShipmentNumber": "Next Shipment Number",
  "_noSlipDups": "No Slip # Duplications",
  "_number": "Number",
  "_orderToQuantity": "Order To Quantity",
  "_orderMultipleQuantity": "Order Multiple Quantity",
  "_postSiteChanges": "Post Site Changes",
  "_postItemSiteChanges": "Post Item Site Changes",
  "_postCountTagToDefault": "When Count Tag Qty exceeds Slip Qty",
  "_postToDefaultLocation": "Post to Default Loc.",
  "_physicalInventory": "Physical Inventory (Counting)",
  "_purchaseOrder": "Purchase Order",
  "_purchaseOrders": "Purchase Orders",
  "_recallShipment": "Recall Shipment",
  "_recallShipment?": "Are you shure you want to recall this shipment?. If it has been invoiced the invoice will also be deleted.",
  "_receiptQtyTolerancePct": "By the Following Amount (%)",
  "_receive": "Receive",
  "_receiveLocation": "Receive Location",
  "_received": "Received",
  "_recordPPVOnReceipt": "Record Purchase Price Variance on Receipt",
  "_reorderLevel": "Reorder Level",
  "_reporting": "Reporting",
  "_returned": "Returned",
  "_returnLine": "Return Line",
  "_safetyStock": "Safety Stock",
  "_shippingAndReceiving": "Shipping and Receiving",
	"_shipmentNumberPolicy": "Shipment Number Policy",
  "_showUnshipped": "Show Unshipped",
  "_showInvoiced": "Show Invoiced Shipments",
  "_shipped": "Shipped",
  "_shipment": "Shipment",
  "_shipments": "Shipments",
  "_stockLocation": "Stock Location",
  "_toReceive": "To Receive",
  "_toIssue": "To Issue",
  "_unReleased": "Unreleased",
  "_useParameters": "Use Parameters",
  "_useParametersManual": "Use Parameters on Manual Entered Orders",
  "_useStandardCost": "Standard Costs",
  "_useAverageCost": "Average Costs",
  "_vendor": "Vendor",
  "_vendors": "Vendors",
  "_vendorType": "Vendor Type",
  "_warnIfReceiptQtyDiffers": "Warn if PO Receipt Qty differs from receivable Qty"
});
