//============= BEGIN GENERATED CONTENT ==============
/** @note
  This file is automatically generated during the build process. Altering it will
  do nothing as it will be rewritten during the next build. Altering it during
  development will tell the development server (sc-server) to rebuilt it.
*/
XM.__LOADABLEINFO__ = {

  //== Deferred Plugins and XBOs ==
  DEFERRED: [
    {
      name: "Crm",
      load: "deferred",
      type: "plugin",
      module: "xm/crm",
    },
    {
      name: "Dashboard",
      load: "deferred",
      type: "plugin",
      menu: NO,
      module: "xm/dashboard",
    },
    {
      name: "Login",
      load: "deferred",
      type: "plugin",
      menu: NO,
      module: "xm/login",
    },
    {
      name: "Account",
      type: "xbo",
      load: "deferred",
      core: NO,
      module: "xm/account",
    },
    {
      name: "Activity",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/activity",
    },
    {
      name: "Address",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/address",
    },
    {
      name: "Alarm",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/alarm",
    },
    {
      name: "Characteristic",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/characteristic",
    },
    {
      name: "Comment",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/comment",
    },
    {
      name: "Contact",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/contact",
    },
    {
      name: "Currency",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/currency",
    },
    // {
    //   name: "Document",
    //   type: "xbo",
    //   load: "deferred",
    //   core: YES,
    //   module: "xm/document",
    // },
    {
      name: "Incident",
      type: "xbo",
      load: "deferred",
      core: NO,
      module: "xm/incident",
    },
    {
      name: "Item",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/item",
    },
    {
      name: "Opportunity",
      type: "xbo",
      load: "deferred",
      core: NO,
      module: "xm/opportunity",
    },
    {
      name: "Priority",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/priority",
    },
    {
      name: "Project",
      type: "xbo",
      load: "deferred",
      core: NO,
      module: "xm/project",
    },
    {
      name: "Site",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/site",
    },
    {
      name: "ToDo",
      type: "xbo",
      load: "deferred",
      core: NO,
      module: "xm/to_do",
    },
    {
      name: "Type",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/type",
    },
    {
      name: "Unit",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/unit",
    },
    {
      name: "UserAccount",
      type: "xbo",
      load: "deferred",
      core: YES,
      module: "xm/user_account",
    },
  ],

  //== Prefetched Plugins and XBOs ==
  PREFETCHED: [
    {
      name: "Dev",
      load: "inlined",
      type: "plugin",
      menu: NO,
      module: "xm/dev",
    },
  ],
}; // end loadable info

//============= END GENERATED CONTENT ==============
