/*globals XM process global */

global.YES = true;
global.NO = false;

/** @namespace
  
  @extends SC.Object
*/
XM = global.XM = SC.Object.create(
  /** @scope XM.prototype */ {

  NAMESPACE: "XM",
  VERSION: "4.0.0ALPHA",
  
  /**
    Numbers are manually generated.
  */
  MANUAL_NUMBER: 'M',

  /** 
    Numbers are automatically generated by the server.
  */
  AUTO_NUMBER: 'A',

  /**
    Numbers are automatically generated, but can be over-ridden by the user.
  */
  AUTO_OVERRIDE_NUMBER: 'O',
  
  MONEY_SCALE: 2,
  QTY_SCALE: 6,
  QTY_PER_SCALE: 6,
  COST_SCALE: 6,
  SALES_PRICE_SCALE: 4,
  PURCH_PRICE_SCALE: 6,
  EXT_PRICE_SCALE:4,
  UOM_RATIO_SCALE: 7,
  PERCENT_SCALE: 4

});

