/*globals XM process global */

global.YES = true;
global.NO = false;

/** @namespace
  
  @extends SC.Object
*/
XM = global.XM = SC.Object.create(
  /** @scope XM.prototype */ {

  NAMESPACE: "XM",
  VERSION: "4.0.0ALPHA",
  
  /**
    Numbers are manually generated.
  */
  MANUAL_NUMBER: 'M',

  /** 
    Numbers are automatically generated by the server.
  */
  AUTO_NUMBER: 'A',

  /**
    Numbers are automatically generated, but can be over-ridden by the user.
  */
  AUTO_OVERRIDE_NUMBER: 'O'

});

