enyo.depends(
  "configure.js",
  "item_site.js",
  "inventory.js",
  "location.js",
  "purchase_order.js",
  "receipt.js",
  "sales_order.js",
  "shipment.js",
  "startup.js",
  "static.js",
  "vendor.js"
);
