enyo.depends(
  "list.js",
  "list_relations.js",
  "navigator.js",
  "workspace.js",
  "scroller.js",
  "groupbox.js",
  "list_relations_box.js",
  "list_relations_editor_box.js",
  "comment_box.js",
  "assignment_box.js",
  "documents_box.js",
  "search.js"
);
