// ==========================================================================
// Project:   XT` Strings
// Copyright: ©2011 OpenMFG LLC, d/b/a xTuple
// ==========================================================================
/*globals XT */

// Place strings you want to localize here.  In your app, use the key and
// localize it using "key string".loc().  HINT: For your key names, use the
// english string with an underscore in front.  This way you can still see
// how your UI will look and you'll notice right away when something needs a
// localized string added to this file!
//

SC.stringsFor("en_US", {

// ********
// Errors
// ********

  "_commentTypeIsRequired": "Comment Type is Required",
  "_characteristicIsRequired": "A Characteristic is required.",
  "_errorCode":"Error Code",
  "_errorIsUnknown": "An unknown error has occurred",
  "_nameIsRequired": "A Name is required",
  "_numberIsRequired": "Number is a required field for this record",
  "_recordConflict": "Record Conflict",
  "_recordExistsCode": "A record already exists with this code.",
  "_recordExistsNumber": "A record already exists with this number.",
  "_recordIncomplete": "Record Incomplete",
  "_unknownError": "Unknown Error",
  "_usernameInvalid": "The Username is invalid",

// ********
// Labels
// ********

  "_account": "Account",
  "_accounting": "Accounting",
  "_accountName": "Account Name",
  "_accountNumber": "Account #",
  "_accounts": "Accounts",
  "_acquiringSessionId": "Acquiring session id",
  "_actions": "Actions",
  "_active": "Active",
  "_activities": "Activities",
  "_actualClose": "Actual Close",
  "_actualDate": "Actual Date",
  "_actualHrs": "Actual Hrs.",
  "_address": "Address",
  "_additional": "Additional",
  "_aim": "AIM",
  "_alarms": "Alarms",
  "_alternate": "Alternate",
  "_amount": "Amount",
  "_applications": "Applications",
  "_apply": "Apply",
  "_assignableOrders": "Assignable Orders",
  "_assigned": "Assigned",
  "_assignedTo": "Assigned To",
  "_attach": "Attach",
  "_balance": "Balance",
  "_balanceHrs": "Balance Hrs.",
  "_billing": "Billing",
  "_billingContact": "Billing Contact",
  "_billTo": "Bill-To",
  "_bomHead": "Bill of Material",
  "_bomItem": "Bill of Material Item",
  "_budgetHrs": "Budget Hrs.",
  "_cancel": "Cancel",
  "_canceled": "Canceled",
  "_category": "Category",
  "_changeAddressAll": "Change Address for All",
  "_changeThisOne": "Change This One",
  "_characteristic": "Characteristic",
  "_characteristics": "Characteristics",
  "_child": "Child",
  "_city": "City",
  "_charges": "Charges",
  "_close": "Close",
  "_closed": "Closed",
  "_comment": "Comment",
  "_comments": "Comments",
  "_commentType": "Comment Type",
  "_commission": "Commission",
  "_competitor": "Competitor",
  "_complete": "Complete",
  "_completed": "Completed",
  "_concept": "Concept",
  "_confirmed": "Confirmed",
  "_contacts": "Contacts",
  "_copy": "Copy",
  "_copyToShipto": "Copy to Ship-to",
  "_correspondenceContact": "Correspondence Contact",
  "_contact": "Contact",
  "_contacts": "Contacts",
  "_converted": "Converted",
  "_couldNotSave":      "Could not save: %@\n%@",
  "_country": "Country",
  "_currency": "Currency",
  "_created": "Created",
  "_createNoMoreThan": "Create no more than",
  "_createRecurring": "Create Recurring",
  "_CRM": "CRM",
  "_crmAccount": "Account",
  "_crmAccounts": "Accounts",
  "_custPrice": "Cust. Price",
  "_custDiscount": "Cust. Discount",
  "_customer": "Customer",
  "_customers": "Customers",
  "_dates": "Dates",
  "_datetime": "Date/Time",
  "_deferred": "Deferred",
  "_delete": "Delete",
  "_description": "Description",
  "_detach": "Detatch",
  "_detail": "Detail",
  "_documents": "Documents",
  "_done": "Done",
  "_due": "Due",
  "_duplicateOf": "Duplicate of",
  "_edit": "Edit",
  "_email": "E-mail",
  "_emailRecipient": "E-mail Recipient",
  "_employee": "Employee",
  "_engineeringReference": "Engineering Reference",
  "_every": "Every",
  "_expActual": "Exp. Actual",
  "_expBudgeted": "Exp. Budgeted",
  "_expBalance": "Exp. Balance",
  "_expensesActual": "Expenses Actual",
  "_expensesBudgeted": "Expenses Budgeted",
  "_expensesBalance": "Expenses Balance",
  "_expires": "Expires",
  "_extended": "Extended",
  "_eventRecipient": "Event Recipient",
  "_facebook": "Facebook",
  "_failedLogin": "Failed to log in",
  "_fax": "Fax",
  "_feedback": "Feedback",
  "_file": "File",
  "_first": "First",
  "_firstName": "First Name",
  "_firstNameAddress": "First Name or Number",
  "_fob": "F.O.B.",
  "_forever": "Forever",
  "_form": "Form",
  "_freight": "Freight",
  "_gantt": "Gantt",
  "_general": "General",
  "_help": "Help",
  "_history": "History",
  "_home": "Home",
  "_hoursActual": "Hours Actual",
  "_hoursBudgeted": "Hours Budgeted",
  "_hoursBalance": "Hours Balance",
  "_hrsActual": "Hrs. Actual",
  "_hrsBudgeted": "Hrs. Budgeted",
  "_hrsBalance": "Hrs. Balance",
  "_image": "Image",
  "_incident": "Incident",
  "_incidents": "Incidents",
  "_individual": "Individual",
  "_initPostbooks": "Postbooks is initializing",
  "_inProcess": "In-Process",
  "_internet": "Internet",
  "_inventory": "Inventory",
  "_inventoryDescription": "Inventory Description",
  "_item": "Item",
  "_items": "Items",
  "_itemSite": "Item Site",
  "_itemSource": "Item Source",
  "_jobTitle": "Job Title",
  "_last": "Last",
  "_lastName": "Last Name",
  "_lastNameAddress": "Last Name or Name",
  "_leadSource": "Lead Source",
  "_ledger": "Ledger",
  "_line1": "Line 1",
  "_line2": "Line 2",
  "_line3": "Line 3",
  "_linkedin": "Linkedin",
  "_list": "List",
  "_loadingSession": "Session loading",
  "_location": "Location",
  "_loggingIn": "Logging in",
  "_loginSuccess": "Successfully Logged In",
  "_logOut": "Log Out",
  "_lotSerial": "Lot/Serial",
  "_manufacturing": "Manufacturing",
  "_margin": "Margin",
  "_mergeAccounts": "Merge Accounts",
  "_mergeContacts": "Merge Contacts",
  "_messaging": "Messaging",
  "_messageRecipient": "Message Recipient",
  "_miscCharge": "Misc. Charge",
  "_miscellaneous": "Miscellaneous",
  "_mobile": "Mobile",
  "_msn": "MSN",
  "_multipleContactsUseAddress": "There are multiple Contacts sharing this Address.",
  "_name": "Name",
  "_needLogin": "Need to log in",
  "_new": "New",
  "_newAccount": "New Account",
  "_newContact": "New Contact",
  "_newIncident": "New Incident",
  "_newOpportunity": "New Opportunity",
  "_newProject": "New Project",
  "_newProspect": "New Prospect",
  "_newToDo": "New To Do",
  "_next": "Next",
  "_noCreatePriv": "You do not have create privileges for this record.",
  "_noDeletePriv": "You do not have delete privileges for this record.",
  "_noEditPriv": "You do not have edit privileges for this record.",
  "_noViewPriv": "You do not have view privileges for this record.",
  "_noForm": "Form has not been set",
  "_noQuery": "Query has not been set",
  "_noRecordType": "Record type has been set.",
  "_none": "None",
  "_noSave": "Don't Save",
  "_notes": "Notes",
  "_notImplemented": "This function has not been implemented yet.",
  "_number": "Number",
  "_ok": "Ok",
  "_onlyAddressesFor": "Only Addresses for %@",
  "_onlyContactsFor": "Only Contacts for %@",
  "_open": "Open",
  "_opportunity": "Opportunity",
  "_opportunities": "Opportunities",
  "_orderActivityByProject": "Order Activity by Project",
  "_ordered": "Ordered",
  "_orderNotes": "Order Notes",
  "_organization": "Organization",
  "_origin": "Origin",
  "_other": "Other",
  "_owner": "Owner",
  "_packDate": "Pack Date",
  "_parent": "Parent",
  "_partner": "Partner",
  "_payables": "Payables",
  "_pending": "Pending",
  "_phone": "Phone",
  "_plan": "Plan",
  "_postalCode": "Postal Code",
  "_preview": "Preview",
  "_previous": "Previous",
  "_price": "Price",
  "_priceUom": "Price UOM",
  "_primaryContact": "Primary Contact",
  "_print": "Print",
  "_priority": "Priority",
  "_private": "Private",
  "_probability": "Probability",
  "_probPct": "Prob. %",
  "_products": "Products",
  "_productDescription": "Product Description",
  "_project": "Project",
  "_projects": "Projects",
  "_prospect": "Prospect",
  "_prospects": "Prospects",
  "_public": "Public",
  "_purchasing": "Purchasing",
  "_purchaseOrder": "Purchase Order",
  "_purchaseOrderItem": "Purchase Order Item",
  "_purchaseOrders": "Purchase Orders",
  "_qty": "Qty.",
  "_qtyUom": "Qty. UOM",
  "_qualifier": "Qualifier",
  "_quote": "Quote",
  "_quoteDate": "Quote Date",
  "_quoteItem": "Quote Item",
  "_quotes": "Quotes",
  "_rate": "Rate",
  "_receivable": 'Receivable',
  "_receivables": "Receivables",
  "_recurring": "Recurring",
  "_references": "References",
  "_registered": "Registered",
  "_relatedTo": "Related to",
  "_relationship": "Relationship",
  "_relationships": "Relationships",
  "_reload": "Reload",
  "_reports": "Reports",
  "_rescanPrivileges": "Rescan Privileges",
  "_resolved": "Resolved",
  "_resolution": "Resolution", 
  "_role": "Role",
  "_roles": "Roles",
  "_sales": "Sales",
  "_salesOrder": "Sales Order",
  "_salesOrderItem": "Sales Order Item",
  "_salesOrders": "Sales Orders",
  "_salesRep": "Sales Rep.",
  "_save": "Save",
  "_saveAndNew": "Save & New",
  "_saveChanges": "Do you want to save changes you have made?",
  "_schedule": "Schedule",
  "_scheduled": "Scheduled",
  "_search": "Search",
  "_searchThrough": "Search through",
  "_secondaryContact": "Secondary Contact",
  "_serverAvailable": "Server is available",
  "_serverUnavailable": "Server is unavailable",
  "_setup": "Setup",
  "_severity": "Severity",
  "_site": "Site",
  "_shipping": "Shipping",
  "_shippingNotes": "Shipping Notes",
  "_shipTo": "Ship-To",
  "_shipToAddress": "Ship-To Address",
  "_shipToAddresses": "Ship-To Addresses",
  "_shipVia": "Ship Via",
  "_showInactive": "Show Inactive",
  "_skype": "Skype",
  "_sold": "Sold",
  "_source": "Source",
  "_stage": "Stage",
  "_start": "Start",
  "_state": "State",
  "_status": "Status",
  "_streetAddress": "Street Address",
  "_subtotal": "Subtotal",
  "_summary": "Summary",
  "_supplyChain": "Supply Chain",
  "_system": "System",
  "_targetClose": "Target Close",
  "_targetDate": "Target Date",
  "_task": "Task",
  "_tasks": "Tasks",
  "_tax": "Tax",
  "_taxAuth": "Tax Auth.",
  "_taxAuthority": "Tax Authority",
  "_taxZone": "Tax Zone",
  "_terms": "Terms",
  "_timeExpense": "Time & Expense",
  "_timeExpenseHistory": "Time & Expense History",
  "_title": "Title",
  "_toDo": "To Do",
  "_toDoList": "To Do List",
  "_totalExpensesActual": "Total Expenses Actual",
  "_totalExpensesBudgeted": "Total Expenses Budgeted",
  "_totalHoursActual": "Total Hours Actual",
  "_totalHoursBudgeted": "Total Hours Budgeted",
  "_total": "Total",
  "_type": "Type",
  "_twitter": "Twitter",
  "_until": "Until",
  "_url": "URL",
  "_updated": "Updated",
  "_updateOwners": "Update Owners",
  "_undefined": "Undefined",
  "_unsavedChangesExist": "Changes you have made have not been saved and will be lost.",
  "_usedBy": "Used By",
  "_usesOfAddress": "Uses of the Address",
  "_usesOfContact": "Uses of Contact",
  "_user": "User",
  "_users": "Users",
  "_username": "Username",
  "_useSpecificBillingRate": "Use specific billing rate",
  "_useSpecificItem": "Use Specific Item",
  "_utilities": "Utilities",
  "_value": "Value",
  "_vendor": "Vendor",
  "_vendorAddress" : "Vendor Address",
  "_verboseText": "Verbose Text",
  "_web": "Web",
  "_webAddress": "Web Address",
  "_weight": "Weight",
  "_whatToDo": "What would you like to do?",
  "_work": "Work",
  "_workOrder": "Work Order",
  "_workOrders": "Work Orders",
  "_yahoo": "Yahoo"

});
