delete from xt.acttype where acttype_code = 'ToDo';
insert into xt.acttype (
  acttype_nsname,
  acttype_tblname,
  acttype_code,
  acttype_col_uuid,
  acttype_col_editor_key,
  acttype_col_type,
  acttype_col_name,
  acttype_col_active,
  acttype_col_status,
  acttype_col_priority_id, 
  acttype_col_description,
  acttype_col_owner_username,
  acttype_col_assigned_username,
  acttype_col_start_date,
  acttype_col_due_date,
  acttype_col_assigned_date,
  acttype_col_completed_Date,
  acttype_col_parent_uuid
) values (
  'public',
  'todoitem',
  'ToDo',
  'obj_uuid',
  'obj_uuid::text',
  'acttype_code',
  'todoitem_name',
  'todoitem_active',
  'todoitem_status',
  'todoitem_priority_id',
  'todoitem_description',
  'todoitem_owner_username',
  'todoitem_username',
  'todoitem_start_date',
  'todoitem_due_date',
  'todoitem_assigned_date',
  'todoitem_completed_date',
  'null::uuid'
);

insert into xt.acttype (
  acttype_nsname,
  acttype_tblname,
  acttype_code,
  acttype_col_uuid,
  acttype_col_editor_key,
  acttype_col_type,
  acttype_col_name,
  acttype_col_active,
  acttype_col_status,
  acttype_col_priority_id, 
  acttype_col_description,
  acttype_col_owner_username,
  acttype_col_assigned_username,
  acttype_col_start_date,
  acttype_col_due_date,
  acttype_col_assigned_date,
  acttype_col_completed_Date,
  acttype_col_parent_uuid
) values (
  'public',
  'incdt',
  'Incident',
  'incdt.obj_uuid',
  'incdt_number::text',
  'acttype_code',
  'incdt_number::text',
  'incdt_status != ''L''',
  'incdt_status',
  'incdt_incdtpriority_id',
  'incdt_summary',
  'incdt_owner_username',
  'incdt_assigned_username',
  'incdt_timestamp::date',
  'null',
  'null',
  'null',
  'null::uuid'
);

delete from xt.acttype where acttype_code = 'Opportunity';
insert into xt.acttype (
  acttype_nsname,
  acttype_tblname,
  acttype_code,
  acttype_col_uuid,
  acttype_col_editor_key,
  acttype_col_type,
  acttype_col_name,
  acttype_col_active,
  acttype_col_status,
  acttype_col_priority_id, 
  acttype_col_description,
  acttype_col_owner_username,
  acttype_col_assigned_username,
  acttype_col_start_date,
  acttype_col_due_date,
  acttype_col_assigned_date,
  acttype_col_completed_Date,
  acttype_col_parent_uuid,
  acttype_join
) values (
  'public',
  'ophead',
  'Opportunity',
  'ophead.obj_uuid',
  'ophead_number::text',
  'acttype_code',
  'ophead_number',
  'ophead_active',
  'opstage_name',
  'ophead_priority_id',
  'ophead_name',
  'ophead_owner_username',
  'ophead_username',
  'ophead_start_date',
  'ophead_target_date',
  'ophead_assigned_date',
  'ophead_actual_date',
  'null::uuid',
  'join opstage on opstage_id=ophead_opstage_id'
);
