delete from xt.acttype where acttype_code = 'SalesOrder';
insert into xt.acttype (
  acttype_nsname,
  acttype_tblname,
  acttype_code,
  acttype_col_uuid,
  acttype_col_editor_key,
  acttype_col_type,
  acttype_col_name,
  acttype_col_active,
  acttype_col_status,
  acttype_col_priority_id, 
  acttype_col_description,
  acttype_col_owner_username,
  acttype_col_assigned_username,
  acttype_col_start_date,
  acttype_col_due_date,
  acttype_col_assigned_date,
  acttype_col_completed_Date,
  acttype_col_parent_uuid,
  acttype_join
) values (
  'public',
  'cohead',
  'SalesOrder',
  'cohead.obj_uuid',
  'cohead_number',
  'acttype_code',
  'cohead_number',
  'cohead_status = ''O''',
  'cohead_status',
  'null',
  'cust_name',
  'lower(salesrep_number)',
  'lower(salesrep_number)',
  'cohead_orderdate',
  'xt.co_schedule_date(cohead)',
  'cohead_packdate',
  'null',
  'null',
  'join custinfo on cohead_cust_id=cust_id join salesrep on cohead_salesrep_id=salesrep_id'
);

delete from xt.acttype where acttype_code = 'SalesOrderWorkflow';
insert into xt.acttype (
  acttype_nsname,
  acttype_tblname,
  acttype_code,
  acttype_col_uuid,
  acttype_col_editor_key,
  acttype_col_type,
  acttype_col_name,
  acttype_col_active,
  acttype_col_status,
  acttype_col_priority_id, 
  acttype_col_description,
  acttype_col_owner_username,
  acttype_col_assigned_username,
  acttype_col_start_date,
  acttype_col_due_date,
  acttype_col_assigned_date,
  acttype_col_completed_Date,
  acttype_col_action,
  acttype_col_parent_uuid,
  acttype_join
) values (
  'xt',
  'coheadwf',
  'SalesOrderWorkflow',
  'coheadwf.obj_uuid',
  'cohead_number',
  'acttype_code',
  'wf_name',
  'wf_status = ''I''',
  'wf_status',
  'wf_priority_id',
  'wf_description',
  'wf_owner_username',
  'wf_assigned_username',
  'wf_start_date',
  'wf_due_date',
  'wf_assigned_date',
  'wf_completed_date',
  'wf_type',
  'cohead.obj_uuid',
  'join cohead on cohead.obj_uuid=wf_parent_uuid'
);

