enyo.depends(
  "core.js",
  "list.js",
  "navigator.js",
  "pullout.js",
  "workspace.js",
  "groupbox.js",
  "panel.js",
  "repeater_box.js",
  "repeater_box_row.js",
  "comment_box.js",
  "assignment_box.js",
  "search.js",
  "screen_carousel.js"
);
