enyo.depends(
  "list.js",
  "navigator.js",
  "pullout.js",
  "workspace.js",
  "workspace_box.js",
  "repeater_box.js",
  "repeater_box_row.js",
  "comment_box.js",
  "search.js",
  "screen_carousel.js"
);
