/* jshint maxlen: false */
(function () {

  var lang = XT.stringsFor("en_US", {

    "_accountsReceivable": "Accounts Receivable",
    "_americanExpress": 'American Express',
    "_asOf": "As Of",
    "_application": "Application",
    "_applications": "Applications",
    "_appliedAmount": "Applied Amount",
    "_applyARMemos": "Apply A/R Memos",
    "_applyBalanceAs": "Apply Balance As",
    "_applyBalanceToCreditMemo": "Credit Memo",
    "_applyBalanceToCustomerDeposit": "Customer Deposit",
    "_autoCloseARIncident": "Auto Close Incidents when Invoid Paid",
    "_autoCreditWarnLateCustomers": "Credit warn Customers when Late",
    "_billing": "Billing",
    "_billingDescription": "Corporate Relationship Management",
    "_cashReceipt": "Cash Receipt",
    "_cashReceiptApplications": "Cash Receipt Applications",
    "_cashReceipts": "Cash Receipts",
    "_cashReceiptCurrencyMismatchWarning": "Cash Receipt currency {cr_currency} does not match Bank Account Currency {ba_currency}",
    "_certifiedCheck": 'Certified Check',
    "_check": 'Check',
    "_createNewCurrency": "Create New Currency",
    "_credits": "Credits",
    "_creditTaxDiscount": "Credit Taxes for Early Payment Discounts",
    "_customerDeposit": "Customer Deposit",
    "_debits": "Debits",
    "_defaultARIncidentStatus": "Default Incident Category",
    "_defaultAutoCreditWarnGraceDays": "Default Grace Period Days",
    "_discover": 'Discover',
    "_distributionDate": "Distribution Date",
    "_applicationDate": "Application Date",
    "_editAROpenItem": "Edit Receivables",
    "_enableCustomerDeposits": "Enable Customer Deposits",
    "_fundsType": "Type of Funds",
    "_hideApplyToBalance": "Hide 'Apply to Balance' Action",
    "_maintainCashReceipts": "Maintain Cash Receipts",
    "_maintainCurrencies": "Maintain Currencies",
    "_maintainMiscInvoices": "Maintain Invoices",
    "_maintainSalesCategory": "Maintain Sales Category",
    "_mastercard": 'Mastercard',
    "_nextARMemoNumber": "Next Receivables Memo",
    "_nextCashRcptNumber": "Next Cash Receipt",
    "_otherCreditCard": 'Other Credit Card',
    "_orderNumber": "Order #",
    "_other": 'Other',
    "_postCashReceipts": "Post Cash Receipts",
    "_postMiscInvoices": "Post Invoices",
    "_printInvoices": "Print Invoices",
    "_printOnPost": "Print on Post",
    "_receivable": "Receivable",
    "_receivables": "Receivables",
    "_recordReceiptAs": "Record Receipt As",
    "_recurringInvoiceBuffer": "Recurring Invoice Buffer Days",
    "_salesCategories": "Sales Categories",
    "_salesCategory": "Sales Category",
    "_unposted": "Unposted",
    "_taxes": "Taxes",
    "_taxTotal": "Tax Total",
    "_useCustomerDeposit": "Use Customer Deposit",
    "_viewAROpenItems": "View Receivables",
    "_viewCashReceipts": "View Cash Receipts",
    "_viewMiscInvoices": "View Invoices",
    "_visa": 'Visa',
    "_void": "Void",
    "_voidPostedCashReceipts": "Void Posted Cash Receipts",
    "_voidPostedInvoices": "Void Posted Invoices",
    "_wireTransfer": 'Wire Transfer'
  });

  if (typeof exports !== 'undefined') {
    exports.language = lang;
  }
}());
