enyo.depends(
  //"number_widget_test.js"
  //"langTest.js",
  //"KindTest.js",
  //"JsonTest.js",
  //"AsyncTest.js",
  //"AjaxTest.js",
  //"ComponentDispatchTest.js",
  //"ComponentHandlersTest.js",
  //"ControlPropsTest.js",
  //"DecodePackagePathTest.js"
);
