// ==========================================================================
// Project:   XT` Strings
// Copyright: ©2011 OpenMFG LLC, d/b/a xTuple
// ==========================================================================
/*globals XT */

// Place strings you want to localize here.  In your app, use the key and
// localize it using "key string".loc().  HINT: For your key names, use the
// english string with an underscore in front.  This way you can still see
// how your UI will look and you'll notice right away when something needs a
// localized string added to this file!
//

var lang = XT.stringsFor("en_US", {

  // ********
  // Models
  // ********

  "_analysis": "Analysis",
  "_all": "All",
  "_annualy": "Annually",
  "_asset": "Asset",
  "_assigned": "Assigned",
  "_automatic": "Automatic",
  "_automaticOverride": "Override Allowed",
  "_biWeekly": "Bi-Weekly",
  "_closed": "Closed",
  "_commission": "Commission",
  "_completed": "Completed",
  "_concept": "Concept",
  "_confirmed": "Confirmed",
  "_daily": "Daily",
  "_database": "Database",
  "_equity": "Equity",
  "_expense": "Expense",
  "_feedback": "Feedback",
  "_hourly": "Hourly",
  "_individual": "Individual",
  "_information": "Information",
  "_inProcess": "In Process",
  "_liability": "Liability",
  "_manual": "Manual",
  "_monthly": "Monthly",
  "_new": "New",
  "_organization": "Organization",
  "_resolved": "Resolved",
  "_revenue": "Revenue",
  "_salaried": "Salaried",
  "_weekly": "Weekly",

  // ********
  // Labels
  // ********

  "_above": "Above",
  "_abbreviation": "Abbreviation",
  "_abbreviationLong": "Abbreviation Long",
  "_abbreviationShort": "Abbreviation Short",
  "_account": "Account",
  "_accounting": "Accounting",
  "_accountNumber": "Account Number",
  "_accountNumberGeneration": "Account Number Generation",
  "_accountType": "Account Type",
  "_accounts": "Accounts",
  "_active": "Active",
  "_actual": "Actual",
  "_actualClose": "Actual Close",
  "_actualExpenses": "Actual Expenses",
  "_actualExpensesTotal": "Total Expenses Actual",
  "_actualHours": "Actual Hours",
  "_actualHoursTotal": "Total Hours Actual",
  "_additional": "Additional",
  "_address": "Address",
  "_address1": "Address1",
  "_address2": "Address2",
  "_address3": "Address3",
  "_addressCharacteristic": "Address Characteristic",
  "_addressComment": "Address Comment",
  "_addresses": "Addresses",
  "_advanced" : "Advanced",
  "_alarms": "Alarms",
  "_altEmphasisColor": "Alt Emphasis Color",
  "_alternate": "Alternate",
  "_alternateAddresses": "Alternate Addresses",
  "_amount": "Amount",
  "_and": "and",
  "_array": "Array",
  "_assignDate": "Assign Date",
  "_assignedTo": "Assigned To",
  "_attach": "Attach",
  "_averageCost": "Average Cost",
  "_backorder": "Accepts Backorders",
  "_balance": "Balance",
  "_balanceExpensesTotal": "Balance Expenses Total",
  "_balanceForward": "Balance Forward",
  "_balanceHoursTotal": "Balance Hours Total",
  "_balanceMethod": "Balance Method",
  "_basis": "Basis",
  "_bcc": "Bcc",
  "_billingContact": "Billing Contact",
  "_billingRate": "Billing Rate",
  "_billTo": "Bill To",
  "_blanketPurchaseOrders": "Uses Blanket Purchase Orders",
  "_body": "Body",
  "_boolean": "Boolean",
  "_breeder": "Breeder",
  "_budgeted": "Budgeted",
  "_budgetedExpenses": "Budgeted Expenses",
  "_budgetedExpensesTotal": "Total Expenses Budgeted",
  "_budgetedHours": "Budgeted Hours",
  "_budgetedHoursTotal": "Total Hours Budgeted",
  "_byProduct": "By Product",
  "_canCreateUsers": "Can Create Users",
  "_category": "Category",
  "_cc": "Cc",
  "_changeAll?": "Would you like to update the address across them all?",
  "_changeLog": "Change Log",
  "_characteristic": "Characteristic",
  "_characteristicType": "Characteristic Type",
  "_characteristicOption": "Characteristic Option",
  "_class": "Class",
  "_classCode": "Class Code",
  "_classCodes": "Class Codes",
  "_close": "Close",
  "_closeDate": "Close Date",
  "_code": "Code",
  "_configure": "Configure",
  "_commentType": "Comment Type",
  "_commentsEditable": "Comments Editable",
  "_company": "Company",
  "_competitor": "Competitor",
  "_completeDate": "Complete Date",
  "_configureSO": "Configure Sales Orders",
  "_contact": "Contact",
  "_contactRelations": "Contacts",
  "_contacts": "Contacts",
  "_coProduct": "Co-Product",
  "_copyToShipTo": "Copy to Ship To",
  "_costCategories": "Cost Categories",
  "_costCategory": "Cost Category",
  "_costing": "Costing",
  "_costs": "Costs",
  "_county": "County",
  "_correspondenceContact": "Correspondence Contact",
  "_countries": "Countries",
  "_created": "Created",
  "_createdBy": "Created By",
  "_credit": "Credit",
  "_creditHolding": "On Credit Holding",
  "_creditLimit": "Credit Limit",
  "_creditRating": "Credit Rating",
  "_creditStatus": "Credit Status",
  "_creditWarning": "On Credit Warning",
  "_crm": "CRM",
  "_cRM": "CRM",
  "_currencies": "Currencies",
  "_currency": "Currency",
  "_currencyAbbreviation": "Currency Abbreviation",
  "_currencyName": "Currency Name",
  "_currencyNumber": "Currency Number",
  "_currencySymbol": "Currency Symbol",
  "_custPO": "Customer PO",
  "_customerPartNumber": "Customer P/N",
  "_custPrice": "Cust. Price",
  "_customer": "Customer",
  "_customerGroup": "Customer Groups",
  "_customerType": "Customer Type",
  "_customerTypes": "Customer Types",
  "_customerPrice": "Customer Price",
  "_customers": "Customers",
  "_customerProspect": "Customer / Prospect",
  "_data": "Data",
  "_dataState": "Data State",
  "_date": "Date",
  "_days": "Days",
  "_deactivate": "Deactivate",
  "_default": "Default",
  "_defaults": "Defaults",
  "_defaultTaxZone": "Default Tax Zone",
  "_deferred": "Deferred",
  "_detach": "Detach",
  "_detail": "Detail",
  "_description": "Description",
  "_description1": "Description1",
  "_description2": "Description2",
  "_discount": "Discount",
  "_disableExport": "Disable Export",
  "_document": "Document",
  "_documentDate": "Document Date",
  "_documentNumber": "Document #",
  "_documentType": "Document Type",
  "_dueDate": "Due Date",
  "_dueDays": "Due Days",
  "_effective": "Effective",
  "_email": "Email",
  "_emailAddresses": "Email Addresses",
  "_emailProfile": "Email Profile",
  "_emphasisColor": "Emphasis Color",
  "_employee": "Employee",
  "_employeeGroup": "Employee Group",
  "_employeeGroups": "Employee Groups",
  "_employees": "Employees",
  "_end": "End",
  "_endBalance": "End Balance",
  "_ending": "Ending",
  "_endingLabel": "Ending Label",
  "_equals": "Equals",
  "_error": "Error",
  "_errorColor": "Error Color",
  "_eventRecipient": "Event Recipient",
  "_excludeProspects": "Exclude Prospects",
  "_expenseCategories": "Expense Categories",
  "_expenseCategory": "Expense Category",
  "_expenses": "Expenses",
  "_expiredColor": "Expired Color",
  "_expires": "Expires",
  "_expireDate": "Expire Date",
  "_extended": "Extended",
  "_extensions": "Extensions",
  "_extendedPrice": "Extended Price",
  "_extendedDescription": "Extended Description",
  "_extendedPriceScale": "Extended Price Scale",
  "_externalReference": "External Reference",
  "_delivery": "Delivery",
  "_department": "Department",
  "_departments": "Departments",
  "_fax": "Fax",
  "_file": "File",
  "_files": "Files",
  "_filter": "Filter",
  "_filterBy": "Filter By",
  "_financials": "Financials",
  "_firstName": "First Name",
  "_flag": "Flag",
  "_fob": "F.O.B.",
  "_for": "For",
  "_fractional": "Fractional",
  "_freightClass": "Freight Class",
  "_frequency": "Frequency",
  "_freeFormBill": "Allow Free-Form Bill-To",
  "_freeFormShip": "Allow Free-Form Ship-Tos",
  "_freight": "Freight",
  "_freightWeight": "Freight Weight",
  "_from": "From",
  "_fromDate": "From Date",
  "_futureColor": "Future Color",
  "_goodStanding": "In Good Standing",
  "_graceDays": "Grace Days",
  "_grantedPrivileges": "Granted Privileges",
  "_grantedUserAccountRoles": "Granted User Account Roles",
  "_groupSequence": "Group Sequence",
  "_groups": "Groups",
  "_header": "Header",
  "_history": "History",
  "_holdType": "Hold Type",
  "_home": "Home",
  "_honorific": "Honorific",
  "_honorifics": "Honorifics",
  "_hours": "Hours",
  "_hrs": "hrs.",
  "_image": "Image",
  "_images": "Images",
  "_inactive": "Inactive",
  "_incident": "Incident",
  "_incidentCategories": "Incident Categories",
  "_incidentCategory": "Incident Category",
  "_incidentChangedStatus": "The status of the following incident has been changed to {status}",
  "_incidentCreatedStatus": "The following incident has been created with status {status}",
  "_incidentCreated": "The following incident has been CREATED",
  "_incidentEmailProfile": "Incident Email Profiles",
  "_incidentEmailProfiles": "Incident Email Profiles",
  "_incidentHistory": "Incident History",
  "_incidentNewComment": "A new COMMENT has been added to the following incident",
  "_incidentRelations": "Incidents",
  "_incidentResolution": "Incident Resolution",
  "_incidentResolutions": "Incident Resolutions",
  "_incidents": "Incidents",
  "_incidentSeverities": "Incident Severities",
  "_incidentSeverity": "Incident Severity",
  "_incidentStatus": "Status",
  "_incidentUpdated": "The following incident has been UPDATED",
  "_initials": "Initials",
  "_inventoryUnit": "Inventory Unit",
  "_isActive": "Active",
  "_isAddresses": "Addresses",
  "_isBase": "Base",
  "_isContacts": "Contacts",
  "_isDefault": "Default",
  "_isDeleted": "Deleted",
  "_isEmployees": "Employees",
  "_isEvent": "Event",
  "_isFractional": "Fractional",
  "_isIncidents": "Incidents",
  "_isItemWeight": "Item Weight",
  "_isItems": "Items",
  "_isMessage": "Message",
  "_isOpportunities": "Opportunities",
  "_isPicklist": "Picklist",
  "_isPosted": "Posted",
  "_isPrinted": "Printed",
  "_isPublic": "Public",
  "_isSold": "Sold",
  "_isSearchable": "Searchable",
  "_isSystem": "System",
  "_item": "Item",
  "_itemConversion": "Item Conversion",
  "_itemNumber": "Item Number",
  "_itemSite": "Item Site",
  "_itemSites": "Item Sites",
  "_itemType": "Item Type",
  "_itemUnitConversion": "Item Unit Conversion",
  "_itemUnitType": "Item Unit Type",
  "_items": "Items",
  "_jobTitle": "Job Title",
  "_kit": "Kit",
  "_language": "Language",
  "_lastName": "Last Name",
  "_latestComment": "Latest Comment",
  "_ledgerAccount": "Ledger Account",
  "_ledgerAccounts": "Ledger Accounts",
  "_limitToList": "Limit to List",
  "_line1": "Line1",
  "_line2": "Line2",
  "_line3": "Line3",
  "_lineItems": "Line Items",
  "_lineNumber": "Line Number",
  "_lines": "Lines",
  "_list" : "List",
  "_listPrice": "List Price",
  "_listPriceDiscount": "List Price Discount",
  "_locale": "Locale",
  "_login": "Login",
  "_logout": "Logout",
  "_lotSerial": "Lot/Serial",
  "_manager": "Manager",
  "_mainAddress": "Main Address",
  "_manufactured": "Manufactured",
  "_map": "Map",
  "_margin": "Margin",
  "_markup": "Markup",
  "_mask": "Mask",
  "_match": "Match",
  "_maximum": "Maximum",
  "_menu": "Menu",
  "_messageRecipient": "Message Recipient",
  "_middleName": "Middle Name",
  "_miscCharge": "Misc. Charge",
  "_module": "Module",
  "_monthExpire": "Month Expire",
  "_multiple": "Multiple",
  "_name": "Name",
  "_neither": "Neither",
  "_nextNumber": "Next Number",
  "_nextCheckNumber": "Next Check Number",
  "_notes": "Notes",
  "_notSold": "Not Sold",
  "_number": "Number",
  "_object": "Object",
  "_offset": "Offset",
  "_other": "Other",
  "_openBalance": "Open Balance",
  "_openDate": "Open Date",
  "_openItems": "Open Items",
  "_opportunities": "Opportunities",
  "_opportunity": "Opportunity",
  "_opportunityRelations": "Opportunities",
  "_opportunitySource": "Opportunity Source",
  "_opportunitySources": "Opportunity Sources",
  "_opportunityStage": "Opportunity Stage",
  "_opportunityStages": "Opportunity Stages",
  "_opportunityType": "Opportunity Type",
  "_opportunityTypes": "Opportunity Types",
  "_open": "Open",
  "_options": "Options",
  "_order": "Order",
  "_orderDate": "Order Date",
  "_orderNumber": "Order Number",
  "_orderNotes": "Order Notes",
  "_ordered": "Ordered",
  "_outsideProcess": "Outside Process",
  "_owner": "Owner",
  "_packDate": "Pack Date",
  "_packing": "Packing",
  "_paid": "Paid",
  "_partialShip": "Accepts Partial Shipments",
  "_partner": "Partner",
  "_password": "Password",
  "_path": "Path",
  "_pending": "Pending",
  "_percent": "Percent",
  "_period": "Period",
  "_phantom": "Phantom",
  "_phone": "Phone",
  "_plannerCode": "Planner Code",
  "_plannerCodes": "Planner Codes",
  "_planning": "Planning",
  "_pleaseLogin": "Please Login",
  "_policy": "Policy",
  "_post": "Post",
  "_postbooks": "PostBooks",
  "_price": "Price",
  "_priceMode": "Price Mode",
  "_priceUnit": "Price UOM",
  "_priceUnitRatio": "Price Unit Ratio",
  "_primaryContact": "Primary Contact",
  "_primaryEmail": "Primary Email",
  "_printed": "Printed",
  "_priority": "Priority",
  "_priorities": "Priorities",
  "_privilege": "Privilege",
  "_privileges": "Privileges",
  "_probability": "Probability",
  "_productCategories": "Product Categories",
  "_productCategory": "Product Category",
  "_product": "Product",
  "_products": "Products",
  "_profit": "Profit",
  "_project": "Project",
  "_projectAssignedTo": "Project Assigned To",
  "_projectOwner": "Project Owner",
  "_projectRelations": "Projects",
  "_projectStatus": "Project Status",
  "_projectTask": "Project Task",
  "_projectTasks": "Project Tasks",
  "_projectTaskStatus": "Project Task Status",
  "_projects": "Projects",
  "_promiseDate": "Promised Date",
  "_properName": "Proper Name",
  "_propername": "Propername",
  "_prospect": "Prospect",
  "_prospects": "Prospects",
  "_proximo": "Proximo",
  "_public": "Public",
  "_purchased": "Purchased",
  "_purchaseOrderNumber": "Purchase Order",
  "_qualifier": "Qualifier",
  "_quantity": "Quantity",
  "_quantityOrd": "Qty Ordered",
  "_quantityUnit": "Qty UOM",
  "_quantityUnitRatio": "Qty Unit Ratio",
  "_quantityShip": "Qty Shipped",
  "_quote": "Quote",
  "_quoteDate": "Quote Date",
  "_quoteLine": "Quote Line",
  "_quotes": "Quotes",
  "_passwordsDoNotMatch": "Passwords do not Match",
  "_recurrences": "Recurrences",
  "_recurring": "Recurring",
  "_reEnterPassword": "Re-Enter Password",
  "_reference": "Reference",
  "_relationships": "Relationships",
  "_replyTo": "Reply To",
  "_required": "Required",
  "_resolution": "Resolution",
  "_return": "Return",
  "_roles": "Roles",
  "_salesOrder": "Sales Order",
  "_salesOrders": "Sales Orders",
  "_salesOrderLine": "Sales Order Line",
  "_salesOrderDate": "Sales Order Date",
  "_salesRep": "Sales Rep",
  "_salesReps": "Sales Reps",
  "_saleType": "Sale Type",
  "_saleTypes": "Sale Types",
  "_schedule": "Schedule",
  "_scheduleDate": "Schedule Date",
  "_secondaryContact": "Secondary Contact",
  "_selectOrganization": "Select Organization",
  "_sense": "Sense",
  "_sequence": "Sequence",
  "_series": "Series",
  "_sessionTimedOut": "Your session has timed out",
  "_settings": "Settings",
  "_setup": "Setup",
  "_severity": "Severity",
  "_shift": "Shift",
  "_shifts": "Shifts",
  "_shipping": "Shipping",
  "_shipCharge": "Shipping Charges",
  "_shipComplete": "Ship Complete",
  "_shipForm": "Shipping Form",
  "_shipVia": "Ship Via",
  "_shipTo": "Ship To",
  "_shipZone": "Ship Zone",
  "_shipZones": "Ship Zones",
  "_shippingNotes": "Shipping Notes",
  "_site": "Site",
  "_siteCode": "Site Code",
  "_siteType": "Site Type",
  "_siteTypes": "Site Types",
  "_sites": "Sites",
  "_showClosed": "Show Closed",
  "_showCompleted": "Show Complete",
  "_showCompletedOnly": "Show Complete Only",
  "_showExpired": "Show Expired",
  "_showInactive": "Show Inactive",
  "_sold": "Sold",
  "_soldRanking": "Sold Ranking",
  "_source": "Source",
  "_sourceType": "Source Type",
  "_stage": "Stage",
  "_standardCost": "Standard Cost",
  "_start": "Start",
  "_startDate": "Start Date",
  "_states": "States",
  "_status": "Status",
  "_string": "String",
  "_subject": "Subject",
  "_subtotal": "Subtotal",
  "_suffix": "Suffix",
  "_summary": "Summary",
  "_symbol": "Symbol",
  "_system": "System",
  "_target": "Target",
  "_targetClose": "Target Close",
  "_targetType": "Target Type",
  "_task": "Task",
  "_tasks": "Tasks",
  "_tax": "Tax",
  "_taxCode": "Tax Code",
  "_taxType": "Tax Type",
  "_taxAssignment": "Tax Assignment",
  "_taxAuthority": "Tax Authority",
  "_taxClass": "Tax Class",
  "_taxRate": "Tax Rate",
  "_taxRegistration": "Tax Registrations",
  "_taxZone": "Tax Zone",
  "_terms": "Terms",
  "_text": "Text",
  "_time": "Time",
  "_to": "To",
  "_toDate": "To Date",
  "_toDo": "To Do",
  "_toDoRelations": "To Dos",
  "_toDoStatus": "To Do Status",
  "_toDos": "To Dos",
  "_tooling": "Tooling",
  "_total": "Total",
  "_totals": "Totals",
  "_toUnit": "To Unit",
  "_trigger": "Trigger",
  "_type": "Type",
  "_unit": "Unit",
  "_unitPrice": "Net Unit Price",
  "_unitCosts": "Unit Costs",
  "_units": "Units",
  "_unitType": "Unit Type",
  "_unknown": "(unknown)",
  "_unitCost": "Unit Cost",
  "_uom": "UOM",
  "_updated": "Updated",
  "_updatedBy": "Updated By",
  "_url": "Link",
  "_urls": "Links",
  "_useDescription": "Use Description",
  "_useEnhancedAuth": "Use Enhanced Authentication",
  "_userAccount": "User Account",
  "_userAccounts": "User Accounts",
  "_userAccountRole": "User Account Role",
  "_userAccountRoles": "User Account Roles",
  "_username": "Username",
  "_usesPurchaseOrders": "Uses Purchase Orders",
  "_validator": "Validator",
  "_value": "Value",
  "_version": "Version",
  "_voucher": "Voucher",
  "_wage": "Wage",
  "_wageType": "Wage Type",
  "_warningColor": "Warning Color",
  "_web": "Web",
  "_webAddress": "Web Address",
  "_welcome": "Welcome",
  "_wholesalePrice": "Wholesale Price",
  "_xtuplePostbooks": "PostBooks",

  // ********
  // Placeholders
  // ********

  "_noAccountName": "No Account Name",
  "_noAddress": "No Address",
  "_noCategory": "No Category",
  "_noCloseTarget": "No Close Target",
  "_noContact": "No Contact",
  "_noEmail": "No Email",
  "_noExpiration": "No Expiration",
  "_noJobTitle": "No Job Title",
  "_noName": "No Name",
  "_noNumber": "No Number",
  "_noPhone": "No Phone",
  "_noPriority": "No Priority",
  "_noPurchaseOrder": "No Purchase Order Number",
  "_noSalesRep": "No Sales Rep",
  "_noSeverity": "No Severity",
  "_noStage": "No Stage",
  "_noStatus": "No Status",
  "_noTerms": "No Terms",
  "_noType": "No Type",

  // ********
  // Permissions
  // ********
  "_alterPackDate": "Alter Pack Date",
  "_configureCRM": "Configure CRM",
  "_configureImportExport": "Configure Import Export",
  "_configurePM": "Configure Project",
  "_createNewCurrency": "Create New Currency",
  "_deleteItemMasters": "Delete Item Masters",
  "_editOthersComments": "Edit Others Comments",
  "_editOwnComments": "Edit Own Comments",
  "_editOwner": "Edit Owner",
  "_firmSalesOrder": "Firm Sales Order Line",
  "_maintainAddresses": "Maintain Addresses",
  "_maintainAllCRMAccounts": "Maintain All Accounts",
  "_maintainAllContacts": "Maintain All Contacts",
  "_maintainAllIncidents": "Maintain All Incidents",
  "_maintainAllOpportunities": "Maintain All Opportunities",
  "_maintainAllProjects": "Maintain All Projects",
  "_maintainAllToDoItems": "Maintain All To-Do Items",
  "_maintainClassCodes": "Maintain Class Codes",
  "_maintainCommentTypes": "Maintain Comment Types",
  "_maintainCountries": "Maintain Countries",
  "_maintainCurrencies": "Maintain Currencies",
  "_maintainCurrencyRates": "Maintain Currency Rates",
  "_maintainCustomerGroups": "Maintain Customer Groups",
  "_maintainExtensions": "Maintain Extensions",
  "_maintainFreightClasses": "Maintain Freight Classes",
  "_maintainImages": "Maintain Images",
  "_maintainItemMasters": "Maintain Item Masters",
  "_maintainProductCategories": "Maintain Product Categories",
  "_maintainQuotes": "Maintain Quotes",
  "_maintainSalesOrders": "Maintain Sales Orders",
  "_maintainSaleTypes": "Maintain Sale Types",
  "_maintainSalesReps": "Maintain Sales Reps",
  "_maintainStates": "Maintain States",
  "_maintainUOMs": "Maintain Units of Measure",
  "_maintainUsers": "Maintain Users",
  "_maintainIncidentCategories": "Maintain Incident Categories",
  "_maintainIncidentPriorities": "Maintain Incident Priorities",
  "_maintainIncidentResolutions": "Maintain Incident Resolutions",
  "_maintainIncidentSeverities": "Maintain Incident Severities",
  "_maintainOpportunitySources": "Maintain Opportunity Sources",
  "_maintainOpportunityStages": "Maintain Opportunity Stages",
  "_maintainOpportunityTypes": "Maintain Opportunity Types",
  "_maintainPartners": "Maintain Partners",
  "_maintainPersonalCRMAccounts": "Maintain Personal Accounts",
  "_maintainPersonalContacts": "Maintain Personal Contacts",
  "_maintainPersonalIncidents": "Maintain Personal Incidents",
  "_maintainPersonalOpportunities": "Maintain Personal Opportunities",
  "_maintainPersonalProjects": "Maintain Personal Projects",
  "_maintainPersonalToDoItems": "Maintain Personal To-Do Items",
  "_maintainTaxAssignments": "Maintain Tax Assignments",
  "_maintainTaxClasses": "Maintain Tax Classes",
  "_maintainTaxCodes": "MaintainTaxCodes",
  "_maintainTaxReconciliations": "Maintain Tax Reconciliations",
  "_maintainTaxRegistrations": "Maintain Tax Registrations",
  "_maintainTaxTypes": "Maintain Tax Types",
  "_maintainTaxZones": "Maintain Tax Zones",
  "_maintainTerms": "Maintain Terms ",
  "_maintainTitles": "Maintain Titles",
  "_overridePrice": "Override Price",
  "_overrideSODate": "Override Order Date",
  "_overrideTax": "Override Tax Type",
  "_reassignToDoItems": "Edit Assign To",
  "_showMarginsOnSalesOrder": "Show Margins",
  "_updateCustomerCreditStatus": "Update Credit Status",
  "_viewAddresses": "View Addresses",
  "_viewAllCRMAccounts": "View All Accounts",
  "_viewAllContacts": "View All Contacts",
  "_viewAllIncidents": "View All Incidents",
  "_viewAllOpportunities": "View All Opportunities",
  "_viewAllProjects": "View All Projects",
  "_viewAllToDoItems": "View All To-Do Items",
  "_viewCosts": "View Costs",
  "_viewClassCodes": "View Class Codes",
  "_viewCurrencyRates": "View Currency Rates",
  "_viewCustomerGroups": "View Customer Groups",
  "_viewDepartments": "View Departments",
  "_viewFreightClasses": "View Freight Classes",
  "_viewItemMasters": "View Item Masters",
  "_viewPersonalCRMAccounts": "View Personal Accounts",
  "_viewPersonalContacts": "View Personal Contacts",
  "_viewPersonalIncidents": "View Personal Incidents",
  "_viewPersonalOpportunities": "View Personal Opportunities",
  "_viewPersonalProjects": "View Personal Projects",
  "_viewPersonalToDoItems": "View Personal To-Do Items",
  "_viewProductCategories": "View Product Categories",
  "_viewQuotes": "View Quotes",
  "_viewSaleTypes": "View Sale Types",
  "_viewSalesOrders": "View Sales Orders",
  "_viewSalesReps": "View Sales Reps",
  "_viewTaxAssignments": "View Tax Assignments",
  "_viewTaxClasses": "View Tax Classes",
  "_viewTaxCodes": "View Tax Codes",
  "_viewTaxReconciliations": "View Tax Reconciliations",
  "_viewTaxRegistrations": "View Tax Registrations",
  "_viewTaxTypes": "View Tax Types",
  "_viewTaxZones": "View Tax Zones",
  "_viewTerms": "View Terms",
  "_viewUOMs": "View Units of Measure",
  "_viewTitles": "View Honorifics",

  // ********
  // Messages
  // ********

  "_accountExists": "This number is currently assigned to an Account.",
  "_assignedToRequiredAssigned": "Assigned to is required when status is 'Assigned'",
  "_attributeIsRequired": "{attr} is required.",
  "_attributeTypeMismatch": "The value of '{attr}' must be type: {type}.",
  "_attributeNotInSchema": "'{attr}' does not exist in the schema.",
  "_attributeReadOnly": "Can not edit read only attribute(s).",
  "_automaticFreight": "Manually clearing the freight will enable automatic Freight recalculations.",
  "_characteristicContextRequired": "You must set at least one characteristic context to true.",
  "_continue?": " Do you want to continue?",
  "_convertAccount": "Convert this Account to a Customer?",
  "_convertAccountEmployee": "Convert this Account to an Employee?",
  "_convertAccountProspect": "Convert this Account to a Prospect?",
  "_convertAccountSalesRep": "Convert this Account to a SalesRep?",
  "_convertAccountTaxAuthority": "Convert this Account to a Tax Authority?",
  "_convertProspect": "Convert this Prospect to a Customer?",
  "_customerExists": "A customer with this number already exists.",
  "_customerOrProspect": "Would you like to create a new Customer or a new Prospect?",
  "_datasourceError": "Data source error: {error}",
  "_duplicateValues": "Duplicate values are not allowed.",
  "_exitPageWarning": "You are about to leave the xTuple application.",
  "_lengthInvalid": "Length of {attr} must be {length}.",
  "_manualFreight": "Manually editing the freight will disable automatic freight recalculations.",
  "_mustSave": "You must save your changes before proceeding.",
  "_nameRequired": "A name is required.",
  "_noPriceFound": "This item is marked as exclusive and no qualifying price was found.",
  "_noPurchase": "This item may not be purchased in this date. Please select another date or item.",
  "_noReschedule": "No Items can be rescheduled because there are no valid price schedules for the date entered.",
  "_partialReschedule": "Some exclusive items may not be rescheduled because there is no valid price schedule for the date entered.",
  "_productCategoryRequiredOnSold": "A Product Category is required for sold items.",
  "_prospectExists": "This number is currently assigned to a Prospect.",
  "_recalculateAll?": "Do you want to recalculate all prices line items, taxes, and freight ?",
  "_recursiveParentDisallowed": "Record is not allowed to reference itself as the parent.",
  "_recordNotFound": "Record not found.",
  "_recordStatusNotEditable": "Record with status of `{status}` is not editable.",
  "_rescheduleAll": "Changing this date will update the Schedule Date on all editable line items.",
  "_updateFractional": "The quantity ordered and unit of measure selected will result in a fractional inventory qty for this item. This item does not allow fractional quantities; the quantity will be updated accordingly.",
  "_updatePrice?": "You have changed the price basis, do you want to update the Price?",
  "_valueExists": "Record with {attr} of '{value}' already exists.",
  "_whatToDo": "What would you like to do?",
  "_endPriorToStart" : "{start} Date must be prior to {end} Date."
});
