create or replace function private.create_xm_view() returns trigger as $$
-- Copyright (c) 1999-2011 by OpenMFG LLC, d/b/a xTuple. 
-- See www.xm.ple.com/CPAL for the full text of the software license.
declare
  i integer;
  cols text[] := '{}';
  tbls text[] := '{}';
  clauses text[] = '{}';
  comments text = 'System view generated by model tables: WARNING! Do not make changes or add rules directly to this view!';
  rules text[] = '{}';
  query text;
  rec record;
begin

  -- Make sure table is valid
  perform tablename 
  from pg_tables 
  where schemaname = new.model_schemaname 
    and tablename = new.model_tablename;

  if (not found) then
    raise exception 'Table % not found', new.table;
  end if;
  
  -- Loop through models and build components
  i := 1;
  
  for rec in
    select model_id, model_columns, model_schemaname, model_tablename, 
      model_conditions, model_rules, model_comment,
      false as ext, null as modelext_join_type, null modelext_join_clause, 
      -1 as modelext_seq
    from only private.model
    where model_name = new.model_name
    union
    select model_id, model_columns, model_schemaname, model_tablename, 
      model_conditions, model_rules, model_comment,
      true as ext, modelext_join_type, null modelext_join_clause, 
      modelext_seq
    from private.modelext
    where model_name = new.model_name
    order by modelext_seq, model_id
  loop
    cols := cols || rec.model_columns;

    -- Concatenate join clauses on tables when specified
    if not rec.ext then
      tbls[i] = rec.model_schemaname || '.' || rec.model_tablename;
    elsif (rec.join_type is not null) then
      tbls[i] = rec.join_type || ' ' || rec.model_schemaname || '.' || rec.model_tablename || ' on (' || rec.model_join_clause || ')';
    else
      tbls[i] = ', ' || rec.model_schemaname || '.' || rec.model_tablename;
    end if;
    
    clauses := clauses || rec.model_conditions;
    
    rules := rules || rec.model_rules;

    if (rec.model_comment is not null) then
      comments := comments || '

'  || rec.model_comment;
    end if;
    
    i := i + 1;
  end loop;

  -- Validate colums
  if array_length(cols, 1) = 0 then
    raise exception 'There must be at least one column defined on the model.';
  end if;

  -- Remove the old view
  perform dropIfExists('VIEW', new.model_name, 'xm');
  
  -- Build query to create the new view
  query := 'create view xm.' || new.model_name || ' as ' ||
         'select ' || array_to_string(cols, ', ') ||
         ' from ' || array_to_string(tbls, ' ');

  if array_length(clauses, 1) > 0 then
    query := query || ' where ' || array_to_string(clauses, ' and ');
  end if;

  -- Create the view
  execute query;

  -- Add comment
  query := 'comment on view xm.' || new.model_name || E' is \'' || comments || E'\''; 

  execute query;
  
  -- Apply the rules
  for rec in
    select unnest(rules) as rule
  loop
    execute rec.rule;
  end loop;

  return new;
  
end;
$$ language 'plpgsql';
