enyo.depends(
  "menu.js",
  "input.js",
  "checkbox.js",
  "number.js",
  "text_area.js",
  "picker.js",
  "characteristics.js",
  "address.js",
  "date.js",
  "completer.js",
  "combobox.js",
  "relation.js",
  "parameter.js",
  "file_input.js",
  "toggle_button.js",
	"icon_button.js",
  "chart.js"
);
