// ==========================================================================
// Project:   XT` Strings
// Copyright: ©2011 OpenMFG LLC, d/b/a xTuple
// ==========================================================================
/*globals XT */

// Place strings you want to localize here.  In your app, use the key and
// localize it using "key string".loc().  HINT: For your key names, use the
// english string with an underscore in front.  This way you can still see
// how your UI will look and you'll notice right away when something needs a
// localized string added to this file!
//

SC.stringsFor("en_US", {

  // ********
  // Labels
  // ********

  "_abbreviation": "Abbreviation %@",
  "_abbreviationLong": "Abbreviation Long",
  "_abbreviationShort": "Abbreviation Short",
  "_account": "Account",
  "_accountNumber": "Account Number",
  "_accountType": "Account Type",
  "_accounts": "Accounts",
  "_achAccountNumber": "Ach Account Number",
  "_achAccountType": "Ach Account Type",
  "_achBatch": "Ach Batch",
  "_achDestination": "Ach Destination",
  "_achDestinationFederal": "Ach Destination Federal",
  "_achDestinationName": "Ach Destination Name",
  "_achDestinationType": "Ach Destination Type",
  "_achGenerateCheckNumber": "Ach Generate Check Number",
  "_achIndividualName": "Ach Individual Name",
  "_achIndividualNumber": "Ach Individual Number",
  "_achLeadTime": "Ach Lead Time",
  "_achOrigin": "Ach Origin",
  "_achOriginName": "Ach Origin Name",
  "_achOriginType": "Ach Origin Type",
  "_achRoutingNumber": "Ach Routing Number",
  "_actual": "Actual",
  "_actualClose": "Actual Close",
  "_actualExpenses": "Actual Expenses",
  "_actualExpensesTotal": "Total Expenses Actual",
  "_actualHours": "Actual Hours",
  "_actualHoursTotal": "Total Hours Actual",
  "_additional": "Additional",
  "_address": "Address",
  "_address1": "Address1",
  "_address2": "Address2",
  "_address_characteristic": "Address Characteristic",
  "_address_comment": "Address Comment",
  "_adjustmentTaxes": "Adjustment Taxes",
  "_alarms": "Alarms",
  "_aliasNumber": "Alias Number",
  "_aliases": "Aliases",
  "_allocatedCredit": "Allocated Credit",
  "_altEmphasisColor": "Alt Emphasis Color",
  "_alternate": "Alternate",
  "_alternateAddresses": "Alternate Addresses",
  "_alternateSubtotalLabel": "Alternate Subtotal Label",
  "_alternateTotalLabel": "Alternate Total Label",
  "_amount": "Amount",
  "_americanExpress": "American Express",
  "_applicationDate": "Application Date",
  "_applications": "Applications",
  "_apply": "Apply",
  "_applyBalanceAs": "Apply Balance as",
  "_applyCredit": "Apply Credit",
  "_assignDate": "Assign Date",
  "_assigned": "Assigned",
  "_assignedTo": "Assigned To",
  "_back": "Back",
  "_balance": "Balance",
  "_balanceMethod": "Balance Method",
  "_bankAccount": "Bank Account",
  "_bankAccounts": "Bank Accounts",
  "_bankAccountAdjustmentType": "Bank Account Adjustment Type",
  "_bankAccountType": "Bank Account Type",
  "_bankName": "Bank Name",
  "_bankAccountAdjustment": "Bank Account Adjustment",
  "_bankAccountAdjustment_type": "Bank Account Adjustment Type",
  "_bankReconciliation": "Bank Reconciliation",
  "_bankReconciliationItem": "Bank Reconciliation Item",
  "_bankReconciliationUnreconciled": "Bank Reconciliation Unreconciled",
  "_basis": "Basis",
  "_basisTaxCode": "Basis Tax Code",
  "_beginning": "Beginning",
  "_beginningLabel": "Beginning Label",
  "_billed": "Billed",
  "_billing": "Billing",
  "_billingContact": "Billing Contact",
  "_billtoAddress": "Bill-to Address",
  "_billtoAddress1": "Bill-to Address1",
  "_billtoAddress2": "Bill-to Address2",
  "_billtoAddress3": "Bill-to Address3",
  "_billtoCity": "Bill-to City",
  "_billtoContactPhone": "Bill-to Contact Phone",
  "_billtoCountry": "Bill-to Country",
  "_billtoName": "Bill-to Name",
  "_billtoPostalCode": "Bill-to Postal Code",
  "_billtoState": "Bill-to State",
  "_budget": "Budget",
  "_budgets": "Budgets",
  "_budgetLabel": "Budget Label",
  "_budget_detail": "Budget Detail",
  "_budgetedExpenses": "Budgeted Expenses",
  "_budgetedExpensesTotal": "Total Expenses Budgeted",
  "_budgetedHours": "Budgeted Hours",
  "_budgetedHoursTotal": "Total Hours Budgeted",
  "_canCreateUsers": "Can Create Users",
  "_cancel": "Cancel",
  "_cardType": "Card Type",
  "_cash": "Cash",
  "_cashReceipt": "Cash Receipt",
  "_cashReceipts": "Cash Receipts",
  "_category": "Category",
  "_characteristic": "Characteristic",
  "_characteristicType": "Characteristic Type",
  "_characteristicOption": "Characteristic Option",
  "_characteristics": "Characteristics",
  "_certifiedCheck": "Certified Check",
  "_check": "Check",
  "_checkForm": "Check Form",
  "_checks": "Checks",
  "_child": "Child",
  "_city": "City",
  "_classCode": "Class Code",
  "_closeDate": "Close Date",
  "_closed": "Closed",
  "_code": "Code",
  "_commentType": "Comment Type",
  "_comments": "Comments",
  "_completed": "Completed",
  "_commentsEditable": "Comments Editable",
  "_commission": "Commission",
  "_commissionDue": "Commission Due",
  "_company": "Company",
  "_completeDate": "Complete Date",
  "_concept": "Concept",
  "_confirmed": "Confirmed",
  "_contact": "Contact",
  "_contactRelations": "Contacts",
  "_contacts": "Contacts",
  "_conversionFrom": "Conversion From",
  "_conversionTo": "Conversion To",
  "_conversions": "Conversions",
  "_correspondenceContact": "Correspondence Contact",
  "_costScale": "Cost Scale",
  "_country": "Country",
  "_county": "County",
  "_created": "Created",
  "_createdBy": "Created By",
  "_creditCardPayments": "Credit Card Payments",
  "_creditCards": "Credit Cards",
  "_creditLimit": "Credit Limit",
  "_creditLimitCurrency": "Credit Currency",
  "_creditMemo": "Credit Memo",
  "_creditRating": "Credit Rating",
  "_creditStatus": "Credit Status",
  "_credits": "Credits",
  "_creditsLabel": "Credits Label",
  "_crm": "CRM",
  "_currency": "Currency",
  "_currencyAbbreviation": "Currency Abbreviation",
  "_currencyName": "Currency Name",
  "_currencyNumber": "Currency Number",
  "_currencyRate": "Currency Rate",
  "_currencyScale": "Currency Scale",
  "_currencySymbol": "Currency Symbol",
  "_currency_rate": "Currency Rate",
  "_customLabel": "Custom Label",
  "_customSource": "Custom Source",
  "_customer": "Customer",
  "_customerCreditCard": "Customer Credit Card",
  "_customerCreditCardPayment": "Customer Credit Card Payment",
  "_customerCreditCardPaymentStatus": "Customer Credit Card Payment Status",
  "_customerCreditCardPaymentType": "Customer Credit Card Payment Type",
  "_customerDeposit": "Customer Deposit",
  "_customerPartNumber": "Customer Part Number",
  "_customerPrice": "Customer Price",
  "_customerType": "Customer Type",
  "_customerTypePattern": "Customer Type Pattern",
  "_customerShipto": "Customer Ship-to",
  "_customers": "Customers",
  "_cutOffDay": "Cut Off Day",
  "_dashboard": "Dashboard",
  "_data": "Data",
  "_dataState": "Data State",
  "_date": "Date",
  "_deactivate": "Deactivate",
  "_debitMemo": "Debit Memo",
  "_debits": "Debits",
  "_debitsLabel": "Debits Label",
  "_deferred": "Deferred",
  "_deferredLedgerAccount": "Deferred Ledger Account",
  "_delete": "Delete",
  "_description": "Description",
  "_description1": "Description1",
  "_description2": "Description2",
  "_details": "Details",
  "_differenceLabel": "Difference Label",
  "_disableExport": "Disable Export",
  "_discount": "Discount",
  "_discountDays": "Discount Days",
  "_discountPercent": "Discount Percent",
  "_discountledgerAccount": "Discountledger Account",
  "_discoverCard": "Discover Card",
  "_discrepancyLedgerAccount": "Discrepancy Ledger Account",
  "_distributionDate": "Distribution Date",
  "_distributions": "Distributions",
  "_document": "Document",
  "_documentDate": "Document Date",
  "_documentNumber": "Document #",
  "_documentType": "Document Type",
  "_dueDate": "Due Date",
  "_dueDays": "Due Days",
  "_duplicate": "Duplicate",
  "_effective": "Effective",
  "_email": "Email",
  "_emphasisColor": "Emphasis Color",
  "_end": "End",
  "_endBalance": "End Balance",
  "_endDate": "End Date",
  "_ending": "Ending",
  "_endingLabel": "Ending Label",
  "_errorColor": "Error Color",
  "_eventRecipient": "Event Recipient",
  "_expenseCategory": "Expense Category",
  "_expenseLedgerAccount": "Expense Ledger Account",
  "_expenses": "Expenses",
  "_expense_category": "Expense Category",
  "_expiredColor": "Expired Color",
  "_expires": "Expires",
  "_extended": "Extended",
  "_extendedDescription": "Extended Description",
  "_extendedPriceScale": "Extended Price Scale",
  "_externalReference": "External Reference",
  "_fax": "Fax",
  "_feedback": "Feedback",
  "_file": "File",
  "_files": "Files",
  "_financialLayout": "Financial Layout",
  "_financialLayoutGroup": "Financial Layout Group",
  "_financialLayoutItem": "Financial Layout Item",
  "_financialStatement": "Financial Statement",
  "_financialStatements": "Financial Statements",
  "_firstName": "First Name",
  "_fiscalYear": "Fiscal Year",
  "_for": "For",
  "_fractional": "Fractional",
  "_freight": "Freight",
  "_freightLedgerAccount": "Freight Ledger Account",
  "_freightTaxes": "Freight Taxes",
  "_frequency": "Frequency",
  "_fromUnit": "From Unit",
  "_fromValue": "From Value",
  "_frozen": "Frozen",
  "_fundsType": "Funds Type",
  "_futureColor": "Future Color",
  "_gainLossLedgerAccount": "Gain Loss Ledger Account",
  "_general": "General",
  "_generalLedger": "General Ledger",
  "_generalLedgers": "General Ledger",
  "_graceDays": "Grace Days",
  "_grantedPrivileges": "Granted Privileges",
  "_grantedUserAccountRoles": "Granted User Account Roles",
  "_groupSequence": "Group Sequence",
  "_groups": "Groups",
  "_history": "History",
  "_home": "Home",
  "_honorific": "Honorific",
  "_hours": "Hours",
  "_hrs": "hrs.",
  "_image": "Image",
  "_images": "Images",
  "_incident": "Incident",
  "_incidentRelations": "Incidents",
  "_incidents": "Incidents",
  "_incidentStatus": "Status",
  "_incoTerms": "Inco Terms",
  "_incoTermsSource": "Inco Terms Source",
  "_individual": "Individual",
  "_initials": "Initials",
  "_inProcess": "In Process",
  "_inventoryUnit": "Inventory Unit",
  "_invoice": "Invoice",
  "_invoices": "Invoices",
  "_invoiceDate": "Invoice Date",
  "_invoiceLine": "Invoice Line",
  "_isAcceptsBackorders": "Accepts Backorders",
  "_isAcceptsPartialShip": "Accepts Partial Ship",
  "_isAccounts": "Accounts",
  "_isAchEnabled": "Ach Enabled",
  "_isAchUseVendorInfo": "Ach Use Vendor Info",
  "_isActive": "Active",
  "_isAddresses": "Addresses",
  "_isAlternateBeginning": "Alternate Beginning",
  "_isAlternateBudget": "Alternate Budget",
  "_isAlternateCredits": "Alternate Credits",
  "_isAlternateDebits": "Alternate Debits",
  "_isAlternateDifference": "Alternate Difference",
  "_isAlternateEnding": "Alternate Ending",
  "_isAlternateSubtotal": "Alternate Subtotal",
  "_isAlternateTotal": "Alternate Total",
  "_isBase": "Base",
  "_isContacts": "Contacts",
  "_isCredit": "Credit",
  "_isCustomerPay": "Customer Pay",
  "_isDatabaseUser": "Database User",
  "_isDebit": "Debit",
  "_isDefault": "Default",
  "_isDeleted": "Deleted",
  "_isDiscountable": "Discountable",
  "_isEvent": "Event",
  "_isFlagFor1099": "Flag For1099",
  "_isFractional": "Fractional",
  "_isFreeFormBillto": "Free Form Bill-to",
  "_isFreeFormShipto": "Free Form Ship-to",
  "_isIncidents": "Incidents",
  "_isItemWeight": "Item Weight",
  "_isItems": "Items",
  "_isMatch": "Match",
  "_isMessage": "Message",
  "_isMiscellaneous": "Miscellaneous",
  "_isOpen": "Open",
  "_isOpportunities": "Opportunities",
  "_isPosted": "Posted",
  "_isPrinted": "Printed",
  "_isPublic": "Public",
  "_isQualified": "Qualified",
  "_isReceives1099": "Receives1099",
  "_isReplaced": "Replaced",
  "_isShowBeginning": "Show Beginning",
  "_isShowBeginningBalance": "Show Beginning Balance",
  "_isShowBeginningPercent": "Show Beginning Percent",
  "_isShowBudget": "Show Budget",
  "_isShowBudgetPercent": "Show Budget Percent",
  "_isShowCustom": "Show Custom",
  "_isShowCustomPercent": "Show Custom Percent",
  "_isShowDebitsCredits": "Show Debits Credits",
  "_isShowDebitsCreditsPercent": "Show Debits Credits Percent",
  "_isShowDifference": "Show Difference",
  "_isShowDifferencePercent": "Show Difference Percent",
  "_isShowEndEndingBalance": "Show End Ending Balance",
  "_isShowEnding": "Show Ending",
  "_isShowEndingPercent": "Show Ending Percent",
  "_isShowSubtotal": "Show Subtotal",
  "_isShowTotal": "Show Total",
  "_isSold": "Sold",
  "_isSubtract": "Subtract",
  "_isSummarize": "Summarize",
  "_isSystem": "System",
  "_isUseCustomerDeposit": "Use Customer Deposit",
  "_isVoid": "Void",
  "_item": "Item",
  "_itemConversion": "Item Conversion",
  "_itemNumber": "Item Number",
  "_itemTax": "Item Tax",
  "_itemTaxType": "Item Tax Type",
  "_itemTaxZone": "Item Tax Zone",
  "_itemUnitConversion": "Item Unit Conversion",
  "_itemUnitType": "Item Unit Type",
  "_items": "Items",
  "_jobTitle": "Job Title",
  "_journal": "Journal",
  "_journals": "Journals",
  "_journalNumber": "Journal Number",
  "_language": "Language",
  "_lastName": "Last Name",
  "_layoutType": "Layout Type",
  "_layoutIncomeStatement": "Layout Income Statement",
  "_layoutIncomeStatementDetail": "Layout Income Statement Detail",
  "_layoutIncomeStatementGroup": "Layout Income Statement Group",
  "_ledger": "Ledger",
  "_ledgerAccount": "Ledger Account",
  "_liabilityLedgerAccount": "Liability Ledger Account",
  "_line1": "Line1",
  "_line2": "Line2",
  "_line3": "Line3",
  "_lineNumber": "Line Number",
  "_lines": "Lines",
  "_listPrice": "List Price",
  "_locale": "Locale",
  "_mainAddress": "Main Address",
  "_mask": "Mask",
  "_masterCard": "Master Card",
  "_maximum": "Maximum",
  "_messageRecipient": "Message Recipient",
  "_middleName": "Middle Name",
  "_module": "Module",
  "_monthExpire": "Month Expire",
  "_multiple": "Multiple",
  "_name": "Name",
  "_new": "New",
  "_New…": "New…",
  "_neither": "Neither",
  "_nextCheckNumber": "Next Check Number",
  "_notes": "Notes",
  "_number": "Number",
  "_Open…": "Open…",
  "_offset": "Offset",
  "_other": "Other",
  "_otherCreditCard": "Other Credit Card",
  "_openBalance": "Open Balance",
  "_openDate": "Open Date",
  "_opportunities": "Opportunities",
  "_opportunity": "Opportunity",
  "_opportunityRelations": "Opportunities",
  "_opportunitySource": "Source",
  "_opportunityStage": "Stage",
  "_opportunityType": "Type",
  "_options": "Options",
  "_order": "Order",
  "_orderDate": "Order Date",
  "_orderNumber": "Order Number",
  "_ordered": "Ordered",
  "_organization": "Organization",
  "_owner": "Owner",
  "_overview": "Overview",
  "_paid": "Paid",
  "_parent": "Parent",
  "_password": "Password",
  "_path": "Path",
  "_payable": "Payable",
  "_payables": "Payables",
  "_payableStatus": "Payable Status",
  "_payable_application": "Payable Application",
  "_payable_ledger_accounts": "Payable Ledger Accounts",
  "_payable_pending_application": "Payable Pending Application",
  "_payable_tax_adjustment": "Payable Tax Adjustment",
  "_payablesLedgerAccount": "Payables Ledger Account",
  "_payment": "Payment",
  "_paymentApproval": "Approval",
  "_paymentApprovals": "Approvals",
  "_payments": "Payments",
  "_paymentDate": "Payment Date",
  "_payment_approval": "Payment Approval",
  "_payment_detail": "Payment Detail",
  "_pending": "Pending",
  "_pendingApplicationType": "Pending Application Type",
  "_pendingApplications": "Pending Applications",
  "_percent": "Percent",
  "_percentFinancialLayoutGroup": "Percent Financial Layout Group",
  "_percentLayoutIncomeStatementGroup": "Percent Layout Income Statement Group",
  "_percentScale": "Percent Scale",
  "_percentlayoutIncomeStatementGroup": "Percentlayout Income Statement Group",
  "_period": "Period",
  "_phone": "Phone",
  "_postDate": "Post Date",
  "_postalCode": "Postal Code",
  "_posted": "Posted",
  "_postedBy": "Posted By",
  "_prepaidLedgerAccount": "Prepaid Ledger Account",
  "_prepaidledgerAccount": "Prepaidledger Account",
  "_price": "Price",
  "_priceUnit": "Price Unit",
  "_priceUnitRatio": "Price Unit Ratio",
  "_primaryContact": "Primary Contact",
  "_primaryEmail": "Primary Email",
  "_printed": "Printed",
  "_priority": "Priority",
  "_privilege": "Privilege",
  "_privileges": "Privileges",
  "_probability": "Probability",
  "_productCategory": "Product Category",
  "_product_category": "Product Category",
  "_profitCenter": "Profit Center",
  "_profit_center": "Profit Center",
  "_project": "Project",
  "_projectAssignedTo": "Project Assigned To",
  "_projectOwner": "Project Owner",
  "_projectStatus": "Project Status",
  "_projectTask": "Project Task",
  "_projectTaskStatus": "Project Task Status",
  "_projects": "Projects",
  "_properName": "Proper Name",
  "_propername": "Propername",
  "_purchaseOrderNumber": "Purchase Order",
  "_purchasePriceScale": "Purchase Price Scale",
  "_purpose": "Purpose",
  "_resolved": "Resolved",
  "_qualifier": "Qualifier",
  "_quantity": "Quantity",
  "_quantityPerScale": "Quantity Per Scale",
  "_quantityScale": "Quantity Scale",
  "_quantityUnit": "Quantity Unit",
  "_quantityUnitRatio": "Quantity Unit Ratio",
  "_quarter": "Quarter",
  "_rate": "Rate",
  "_reasonCode": "Reason Code",
  "_reason_code": "Reason Code",
  "_receivable": "Receivable",
  "_receivableLedgerAccount": "Receivable Ledger Account",
  "_receivables": "Receivables",
  "_receivablesLedgerAccount": "Receivables Ledger Account",
  "_recordReceiptAs": "Record Receipt as",
  "_recurrences": "Recurrences",
  "_recurring": "Recurring",
  "_reference": "Reference",
  "_relatedTo": "Related To",
  "_resolution": "Resolution",
  "_routing": "Routing",
  "_sales": "Sales",
  "_salesCategory": "Sales Category",
  "_salesLedgerAccount": "Sales Ledger Account",
  "_salesPriceScale": "Sales Price Scale",
  "_salesRep": "Sales Rep",
  "_save": "Save",
  "_schedule": "Schedule",
  "_Search…": "Search…",
  "_secondaryContact": "Secondary Contact",
  "_sense": "Sense",
  "_sequence": "Sequence",
  "_series": "Series",
  "_severity": "Severity",
  "_shipCharge": "Ship Charge",
  "_shipDate": "Ship Date",
  "_shipVia": "Ship Via",
  "_shipZone": "Ship Zone",
  "_ship_charge": "Ship Charge",
  "_ship_via": "Ship Via",
  "_ship_zone": "Ship Zone",
  "_shipping": "Shipping",
  "_shippingNotes": "Shipping Notes",
  "_shiptoAddress": "Ship-to Address",
  "_shiptoAddress1": "Ship-to Address1",
  "_shiptoAddress2": "Ship-to Address2",
  "_shiptoAddress3": "Ship-to Address3",
  "_shipto": "Ship-to",
  "_shiptoCity": "Ship-to City",
  "_shiptoContactPhone": "Ship-to Contact Phone",
  "_shiptoCountry": "Ship-to Country",
  "_shiptoName": "Ship-to Name",
  "_shiptoPostalCode": "Ship-to Postal Code",
  "_shiptoState": "Ship-to State",
  "_shiptos": "Ship-tos",
  "_showTotal": "Show Total",
  "_source": "Source",
  "_sourceType": "Source Type",
  "_standardJournal": "Standard Journal",
  "_standardJournalGroup": "Standard Journal Group",
  "_start": "Start",
  "_startDate": "Start Date",
  "_state": "State",
  "_states": "States",
  "_status": "Status",
  "_subAccount": "Sub Account",
  "_subtotal": "Subtotal",
  "_subType": "Sub Type",
  "_subtotalLabel": "Subtotal Label",
  "_suffix": "Suffix",
  "_summary": "Summary",
  "_symbol": "Symbol",
  "_target": "Target",
  "_targetClose": "Target Close",
  "_targetType": "Target Type",
  "_tasks": "Tasks",
  "_tax": "Tax",
  "_taxAuthority": "Tax Authority",
  "_taxClass": "Tax Class",
  "_taxCode": "Tax Code",
  "_taxRegistrations": "Tax Registrations",
  "_taxType": "Tax Type",
  "_taxZone": "Tax Zone",
  "_taxes": "Taxes",
  "_terms": "Terms",
  "_termsType": "Terms Type",
  "_text": "Text",
  "_time": "Time",
  "_time/expense": "Time/Expense",
  "_toDo": "To Do",
  "_todoRelations": "To Dos",
  "_toDoStatus": "To Do Status",
  "_toDos": "To Dos",
  "_total": "Total",
  "_totals": "Totals",
  "_toUnit": "To Unit",
  "_toValue": "To Value",
  "_totalLabel": "Total Label",
  "_trialBalance": "Trial Balance",
  "_trialBalances": "Trial Balance",
  "_trigger": "Trigger",
  "_type": "Type",
  "_unit": "Unit",
  "_unitRatioScale": "Unit Ratio Scale",
  "_unitType": "Unit Type",
  "_unit_conversion": "Unit Conversion",
  "_unit_type": "Unit Type",
  "_unreconciled": "Unreconciled",
  "_updated": "Updated",
  "_updatedBy": "Updated By",
  "_url": "Url",
  "_urls": "Urls",
  "_useDescription": "Use Description",
  "_usedForBilling": "Used for Billing",
  "_usedForPayments": "Used for Payments",
  "_userAccount": "User Account",
  "_userAccountRole": "User Account Role",
  "_userAccountRoles": "User Account Roles",
  "_username": "Username",
  "_validator": "Validator",
  "_value": "Value",
  "_varianceLedgerAccount": "Variance Ledger Account",
  "_vendor": "Vendor",
  "_vendorType": "Vendor Type",
  "_vendorTypePattern": "Vendor Type Pattern",
  "_vendors": "Vendors",
  "_visa": "Visa",
  "_voucher": "Voucher",
  "_vouchers": "Vouchers",
  "_voucher_tax": "Voucher Tax",
  "_warningColor": "Warning Color",
  "_webAddress": "Web Address",
  "_wireTransfer": "Wire Transfer",
  "_xtuplePostbooks": "PostBooks",
  "_yearEndLedgerAccount": "Year End Ledger Account",
  "_yearExpire": "Year Expire",

  // ********
  // Messages
  // ********

  "_assignedToRequiredForAssigned": "Assigned to is required when status is assigned.",
  "_charAssignIsRequired": "Characteristics must be assigned to at least one document type.",
  "_commitError": "Commit Error",
  "_currRateDateRangeInvalid": "The date range overlaps with another date range.",
  "_currRateExpireDateInvalid": "The Start Date for this exchange rate is later than the End Date.",
  "_currSymbAbbrRequired": "Either the currency symbol or abbreviation must be supplied.",
  "_dataSourceError": "Data Source Error.",
  "_deleteRecord": "Delete Record?",
  "_dispatchError": "Dispatch Error",
  "_dueDateIsRequired": "Due Date is Required.",
  "_duplicateTaxRegistration": "A Tax Registration already exists for the parameters specified.",
  "_errorCode":"Error Code",
  "_errorIsUnknown": "An unknown error has occurred",
  "_fetchError": "Fetch Error",
  "_firstOrLastNameRequired": "First or last name is required",
  "_idInvalid": "The record requries a valid id issued from the data source.",
  "_loading": "Loading...",
  "_noLineItems": "This document requires at least one line item.",
  "_noAccountName": "No Account Name",
  "_noCategory": "No Category",
  "_noContact": "No Contact",
  "_noDescription": "No Description",
  "_noEmail": "No Email",
  "_noJobTitle": "No Job Title",
  "_noName": "No Name",
  "_noNumber": "No Number",
  "_noPhone": "No Phone", 
  "_noPriority": "No Priority",
  "_noSalesRep": "No Sales Rep",
  "_noSeverity": "No Severity",
  "_noRecords": "No Records",
  "_noResultsFound": "No results were returned for the query.",
  "_noStage": "No Stage",
  "_noTargetDate": "No Target Date",
  "_noTerms": "No Terms",
  "_noType": "No Type",
  "_optionExistsValue": "A option already exists with this Value.",
  "_parentIsInvalid": "This CRM Account cannot be a parent to itself.",
  "_recordConflict": "Record Conflict",
  "_recordExistsKey": "A record already exists with the specified document key.",
  "_recordInvalid": "Record Invalid",
  "_recordIncomplete": "Record Incomplete",
  "_requiredFieldsEmpty": "Required field(s) are empty",
  "_retrieveError": "Retrieve Error",
  "_sameAsBillto": "Same as Bill-to",
  "_taxesGreaterThanAmount": "Taxes can not be greater than the amount.",
  "_totalMustBePositive": "Total Must Be Positive",
  "_unknownError": "Unknown Error",
  "_uniqueNameRequired": "A Currency type already exists with this Abbreviation.",
  "_unsavedChanges": "There are unsaved changes. Save the changes?",
  "_unsavedRecord": "The record has not been saved. Save the record?",
  "_usernameInvalid": "The user name is invalid."
  
});
