var depends = (typeof enyo !== 'undefined') ? enyo.depends : X.depends;
depends(
  "ext",
  "core.js",
  "model_mixin.js",
  "model.js",
  "view.js",
  "simple_model.js",
  "collection.js",
  "static.js",
  "document.js",
  "info.js",
  "comment.js",
  "characteristic.js",
  "alarm.js",
  "settings.js",
  "workflow.js",
  "router.js"
);
