enyo.depends(
  "$lib/underscore",
  "$lib/backbone",
  "$lib/backbone_relational",
  "$lib/layout",
  "$lib/onyx",
  "$lib/globalize",
  "$lib/gts-plugins",
  "$lib/date_format",
  "$lib/socket_io",
  "xt",
  "xm",
  "xv",
  "app.js"
);